= Specimen Shipment Manifest

== Introduction

[v291_section="17.16"]



== General Use Cases / Background

=== Actors
[v291_section="17.16.1.1"]

* Specimen Shipper - The Specimen Shipper actor is an application capable of sending specimen shipments and transmitting the specimen shipment manifest message.

* Specimen Shipment Receiver - The Specimen Shipment Receiver actor is an application capable of receiving specimen shipments as well as specimen shipment manifest messages. Typically this application is associated with a Laboratory. 

=== Activity Diagram
[v291_section="17.16.1.2"]

The following activity diagram illustrates the usage of this message. The message is initially sent from the Specimen Shipper at the point the specimen is shipped. The actual point of transmission of the message could occur as soon as all the contents of the shipment have been identified, and the transporters shipment id has been assigned to the shipment. The specimen shipment receiver will send back transaction using the Specimen Shipment Manifest message indicating the specimen shipment has been accepted or rejected. This normally will occur after the shipment has been physically received and evaluated. Note that this response back is not considered an application acknowledgment, and is certainly not required. Its purpose is to update the shipper with the status of the shipment.

== Technical Specs

xref:technical_specs/R26.adoc[Message - R26 Unsolicited Specimen Shipment Manifest]
