==== Identification of the organism for a susceptibility battery
[v291_section="7.5.5.3"]

The following is the preferred, but not required method of organizing data about antimicrobial susceptibility.

A susceptibility battery may only contain results corresponding to a single organism that has been previously reported in a culture battery.

A susceptibility battery is always a child order to a culture battery. _OBR-29 Parent_ (parent's filler order number) in the susceptibility OBR is equal _to OBR-3 Filler Order Number_ in the parent culture OBR and is used to link the two batteries logically.

The susceptibility battery also contains a linkage back to a particular organism in the culture battery. _OBR-26 Parent Result_ of the susceptibility OBR contains two components--_OBX-3 Observation Identifier_ (code only) and _OBX -4 Observation Sub-ID_ of the OBX in the culture battery which contains the organism name.

The identity of an organism/isolate is expected to be refined over time. When an organism identification changes, the parent culture battery can be resent without resending the child susceptibility battery.

The case may occur where a susceptibility battery is reported on an organism which has not yet been identified. In this case, it is required that a placeholder OBX for the organism name be reported in the corresponding culture battery so that _OBR-26 Parent Result_ in the susceptibility OBR will point to a valid organism OBX in the culture battery. Transmission of an organism OBX (in the culture battery) with the Sub-ID field valued must precede the susceptibility battery which uses the identical Sub-ID in _OBR-26 Parent Result_.

Discussion and examples:

Order micro results (blood culture)

[er7]
MSH|^~\&|LAB1||DESTINATION||19910127105114||ORU^R01^ORU_R01|LAB1003929|...<cr>

PID|...<cr>

PV1|...<cr>

[er7]
ORC|NW|...<cr>
[er7]
OBR|1|A485388^OE|H29847^LAB1|17928-3^BLOOD CULTURE^LN|||...<cr>

Result for culture

[er7]
ORC|RE|...<cr>
[er7]
OBR|1|A485388^OE|H29847^LAB1|17928-3^BLOOD CULTURE ^LN||...<cr>
[er7]
OBX|1|FT|SDES^SOURCE||BLOOD-RAPID||||||F|...<cr>
[er7]
OBX|2|FT|664-3^GRAM STAIN SMEAR^LN||GRAM POSITIVE COCCI IN GROUPS||||||F|...<cr>
[er7]
OBX|3|FT|600-7^MICROORGANISM IDENTIFIED^LN|1|ISOLATE 1||||||F|...<cr>

Result for susceptibility

[er7]
ORC|RE|...<cr>
[er7]
OBR|1|A485388^OE|H29848^LAB1|BT1^SUSCEPTIBILITY BATTERY||||||123^MANSFIELD^CHARLES| ||||||||||||||||600-7&MICROORGANISM IDENTIFIED&LN ^1|||A485388&OE^H29847&LAB1|...<cr>
[er7]
OBX|1|NM|6932-8^PENICILLIN MIC^LN||0.5|||R|||F|...<cr>
[er7]
OBX|2|NM|347-5^NAFCILLIN MIC^LN||1|||R|||F|...<cr>
[er7]
OBX|3|ST|193-3^CLINDAMYCIN MIC^LN||<=0.1|||S|||F|...<cr>

Result for Culture ID

[er7]
ORC|RE|...<cr>
[er7]
OBR|1|A485388^OE|H29847^LAB1|17928-3^BLOOD CULTURE ^LN||...<cr>
[er7]
OBX|1|FT|600-7^ MICROORGANISM IDENTIFIED^LN |1|STAPH EPI||||||F|...<cr>

New result for culture ID

[er7]
ORC|RE|...<cr>
[er7]
OBR|1|A485388^OE|H29847^LAB1|17928-3^BLOOD CULTURE ^LN||...<cr>
[er7]
OBX|1|FT|600-7^MICROORGANISM IDENTIFIED^LN|1|STAPH EPI SERO TYPE 3||||||F|...<cr>

Assumptions

{empty}1) All OBXs in the parent order must employ the same coding scheme.

{empty}2) The Sub-ID of the parent OBXs (result) cannot change.

