= Message - A05 Pre-Admit a Patient
:v291_section: "3.3.5"
:v2_section_name: "ADT/ACK - Pre-Admit a Patient (Event A05)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

An A05 event is sent when a patient undergoes the pre-admission process. During this process, episode-related data is collected in preparation for a patient's visit or stay in a healthcare facility. For example, a pre-admit may be performed prior to inpatient or outpatient surgery so that lab tests can be performed prior to the surgery. This event can also be used to pre-register a non-admitted patient.

The ROL segment has been deprecated and retained for backwards compatiblity purposes only as of v 2.9. The reader is referred to the PRT segment instead.

The PRT - Participation Segment is used in this message to communicate providers not specified elsewhere. Person level providers with an ongoing relationship are reported in the PRT segment following the PID/PD1 segments. Visit level providers (corresponding to the PV1 data) are reported in the PRT segment following the PV1/PV2 segments. Providers related to a specific procedure are reported in the PRT segment following the PR1 segment. Providers related to a specific insurance are reported in the PRT segment following the IN1/IN2/IN3 segments. To communicate the begin- and end-date of the provider, use the _–PRT-11 - Begin Date/Time_ and the _–PRT-12 - End Date/Time_ in the PRT segment, with the applicable _PRT-4 – Role of Participation_. Refer to Chapter 15 for the definition of the PRT segment.

[message_structure-table]

[ack_chor-table]

[ack_message_structure-table]

[ack_chor-table]

