= Message - A06  Change an Outpatient to an Inpatient
:v291_section: "3.3.6"
:v2_section_name: "ADT/ACK - Change an Outpatient to an Inpatient (Event A06)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

An A06 event is sent when a patient who was present for a non-admitted visit is being admitted after an evaluation of the seriousness of the patient's condition. This event changes a patient's status from non-admitted to admitted. The new patient location should appear in _PV1-3 - Assigned Patient Location_, while the old patient location (if different) should appear in _PV1-6 - Prior Patient Location_. The new patient class should appear in _PV1-2 - Patient Class_.

It will be left to implementation negotiation to determine whether disparate systems merely change the patient class, or close and open a new account. The current active account number should appear in field _PID-18 - Patient Account Number_; the prior account number can be included optionally in _MRG-3 - Prior Patient Account Number_. This arrangement is not intended to be a type of merge. The MRG segment is used here only for _MRG-3 - Prior Patient Account Number_. _PV1-19 - Visit Number_ may also be changed during this event.

The fields included when this message is sent should be the fields pertinent to communicate this event. When other important fields change, it is recommended that the A08 (update patient information) event be used in addition.

The ROL segment has been deprecated and retained for backwards compatiblity purposes only as of v 2.9. The reader is referred to the PRT segment instead.

The PRT – Participation Information Segment is used in this message to communicate providers not specified elsewhere. Person level providers with an ongoing relationship are reported in the PRT segment following the PID/PD1 segments. Visit level providers (corresponding to the PV1 data) are reported in the PRT segment following the PV1/PV2 segments. Providers related to a specific procedure are reported in the PRT segment following the PR1 segment. Providers related to a specific insurance are reported in the PRT segment following the IN1/IN2/IN3 segments. To communicate the begin- and end-date of the provider, use the _PRT-11 –Begin Date/Time_ and the _PRT-12 –End Date/Time_ in the PRT segment, with the applicable _PRT-4 – role of Participation_. Refer to Chapter 7 for the definition of the PRT segment.

[message_structure-table]

[ack_chor-table]

[ack_message_structure-table]

[ack_chor-table]

