= Message - A10 Patient Arriving - Tracking 
:v291_section: "3.3.10"
:v2_section_name: "ADT/ACK - Patient Arriving - Tracking (Event A10)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

The A10 event is sent when a patient arrives at a new location in the healthcare facility (inpatient or outpatient). The A09 - patient departing-tracking and A10 events are used when there is a change in a patient's physical location and when this is NOT a change in the official census bed location, as in the case of an outpatient setting. There are three varieties of these non-census location changes involving three different kinds of notification: (a) an unofficial notification of location change prior to the official notification of patient tracking, (b) the patient is in transit between locations for some time, (c) a notification of a temporary location change.

Patient tracking: If the patient is now at a non-temporary location and is not in transit, then _PV1-3 - Assigned Patient Location_ must contain the new patient location and _PV1-6 - Prior Patient Location_ can contain the old patient location.

In transit: This is used when there is some period of time between when the patient leaves his/her old location and when he/she arrives at the new assigned location. If the patient was in transit during the time between the A09 (patient departing-tracking) event and the A10 (patient arriving-tracking) event, then _PV1-3 - Assigned Patient Location_ is used for the new location and _PV1-6 - Prior Patient Location_ should be used for the old location. _PV1-11 - Temporary Location_ and _PV1-43 - Prior Temporary Location_ are not used.

Temporary location: An A10 event can also be used when the patient is being transferred from a temporary location (X-RAY, O/R, LIMBO, or HALLWAY) to the new assigned location. If the patient is arriving at a temporary location (such as the O/R, X-RAY, LIMBO, or HALLWAY), then _PV1-11 - Temporary Location_ would be used to indicate the new temporary location. If the patient is moving from one temporary location to another, then _PV1-43 - Prior Temporary Location_ may also be used. If the patient is arriving at a permanent location from a temporary location, _PV1-3 - Assigned Patient Location_ should be used for the new location, and _PV1-43 - Prior Temporary Location_ should be used for the old location.

The fields included when this message is sent should be the fields pertinent to communicate this event. When other important fields change, it is recommended that the A08 (update patient information) event be used in addition.

*Attention: The DG1 segment was retained for backward compatibility only as of v2.4 and was withdrawn and removed from this message structure as of v2.7.*

[message_structure-table]

[ack_chor-table]

[ack_message_structure-table]

[ack_chor-table]

