= Message - A24 Link Patient Information
:v291_section: "3.3.24"
:v2_section_name: "ADT/ACK - Link Patient Information (Event A24)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

The A24 event is used when the first PID segment needs to be linked to the second PID segment and when both patient identifiers identify the same patient. Linking two or more patients does not require the actual merging of patient information; following a link event, the affected patient data records should remain distinct. For example, this event could be used in a hospital network environment in which there are multiple campuses and in which records need to be linked. For example, hospital A, hospital B, and hospital C would each keep their own records on a patient, but an A24 link event would be sent to a corporate-wide MPI to enable the coupling of ID information with the corporate ID number. It is used for corporate data repositories, etc. This event is not meant to link mothers and babies since a field exists (_PID-21 - Mother's Identifier_) for that purpose. See section link:#patient-record-links[_3.6.3_], "_link:#patient-record-links[Patient record links],_" for a discussion of issues related to implementing patient link messages and MPI issues.

This event can also be used to link two patient identifiers when a patient changes from inpatient to outpatient, or vice versa. This event can also be used to link two visits of the same patient.

The fields included when this message is sent should be the fields pertinent to communicate this event. When other important fields change, it is recommended that the A08 (update patient information) event be used in addition.

[tabset]
A24







