= Message - A42 Merge Visit - Visit Number 
:v291_section: "3.3.42"
:v2_section_name: "ADT/ACK - Merge Visit - Visit Number (Event A42)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

A merge has been done at the visit identifier level. That is, two _PV1-19 - Visit Number_ identifiers have been merged into one.

An A42 event is used to signal a merge of records for a visit that was incorrectly filed under two different visit numbers. The "incorrect source visit number" identified in the MRG segment (_MRG-5 - Prior Visit Number_) is to be merged with the required "correct target visit number" identified in the PV1 segment (_PV1-19 - Visit Number_). The "incorrect source visit number" would then logically never be referenced in future transactions. It is noted that some systems may still physically keep this "incorrect identifier" for audit trail purposes or other reasons associated with database index implementation requirements.

An A42 (merge visit-visit number) event is intended for merging visit records without merging other identifiers. Any other identifiers that were previously associated with the "incorrect source visit number" are now associated with the "correct target visit number."

Each superior identifier associated with this visit identifier level should have the same value in the PID and MRG segments, or the MRG and PV1 segments, as appropriate.

See sections link:#merging-patientperson-information[_3.6.2_&#44;] "link:#merging-patientperson-information[_Merging patient/person information_]," and link:#merge[_3.6.2.1.2_], "link:#merge[_Merge_]," for a discussion of issues related to the implementation of merge messages.

The fields included when this message is sent should be the fields pertinent to communicate this event. When other fields change, it is recommended that the A08 (update patient information) event be used in addition

[tabset]







