= Message - A43 Move Patient Information - Patient Identifier List 
:v291_section: "3.3.43"
:v2_section_name: "ADT/ACK - Move Patient Information - Patient Identifier List (Event A43)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

A move has been done at the patient identifier list level. Identifier to be moved in the _PID-3 - Patient Identifier List_ and _MRG-1 - Prior Patient Identifier List_ will have the same value. The "from" (incorrect source patient ID) and "to" (correct target patient ID) identifiers have different values. See A43 examples in section 5. The identifiers involved in identifying the patient to be moved (_MRG-1 - Prior Patient Identifier List_) may or may not have accounts, which may or may not have visits. In any case, all subordinate data sets associated with the identifier in _MRG-1 - Prior Patient Identifier List_ are moved along with the identifier, from the "incorrect source patient ID" to the "correct target patient ID."

No identifiers subordinate to the identifier (account number, visit number, alternate visit ID) are valued in this message. Specification of these other subordinate identifiers is not required.

This event and the message syntax do, however, allow for the specification of a "new identifier" (_PID-3 - Patient Identifier List_), which may be application and/or implementation specific and therefore require site negotiation.

See sections link:#merging-patientperson-information[_3.6.2_&#44;] "link:#merging-patientperson-information[_Merging patient/person information_]," and link:#move[_3.6.2.1.3_], "link:#move[_Move_]," for a discussion of issues related to the implementation of move messages.

The fields included when this message is sent should be the fields pertinent to communicate this event. When demographic data in other fields change, it is recommended that the A08 (update patient information) event be used in conjunction with this message. However, all PID data associated with the "correct target identifier" (_PID-3 - Patient Identifier List_) are treated as updated information.

[tabset]
A43








