= Message - A44 Move Account Information - Patient Account Number
:v291_section: "3.3.44"
:v2_section_name: "ADT/ACK - Move Account Information - Patient Account Number (Event A44)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

A move has been done at the account identifier level. That is, a _PID-18 - Patient Account Number_ associated with one _PID-3 - Patient Identifier List_ has been moved to another patient identifier list.

An A44 event is used to signal a move of records identified by the _MRG-3 - Prior Patient Account Number_ from the "incorrect source patient identifier list" identified in the MRG segment (_MRG-1 - Prior Patient Identifier List_) to the "correct target patient identifier list" identified in the PID segment (_PID-3 - Patient Identifier List_).

The account number involved in identifying the account to be moved (_MRG-3 - Prior Patient Account Number_) may or may not have visits. In any case, all subordinate data sets associated with the account number in _MRG-3 - Prior Patient Account Number_ are moved along with the account number, from the "incorrect source" ID (_MRG-1 - Prior Patient Identifier List_) to the "correct target" ID (_PID-3 - Patient Identifier List_).

No identifiers subordinate to the account number (visit number, alternate visit ID) are valued in this message.

This event and the message syntax do, however, allow for the specification of a "new identifier" (_PID-18 - Patient Account Number_), which may be application and/or implementation-specific and therefore require site negotiation.

All of the identifiers superior to the account number should be valued in both the MRG segment and the PID segment. In this message, the _PID-3 - Patient Identifier List_ is superior to the account number.

See sections link:#merging-patientperson-information[_3.6.2_&#44;] "link:#merging-patientperson-information[_Merging patient/person information_]," and link:#move[_3.6.2.1.3_], "link:#move[_Move_]," for a discussion of issues related to the implementation of move messages.

The fields included when this message is sent should be the fields pertinent to communicate this event. When demographic data in other fields change, it is recommended that the A08 (update patient information) event be used in conjunction with this message. However, all PID data associated with the "account number" are treated as updated information.

[message_structure-table]

[ack_chor-table]

[ack_message_structure-table]

[ack_chor-table]

