= Message - A45 Move Visit Information - Visit Number
:v291_section: "3.3.45"
:v2_section_name: "ADT/ACK - Move Visit Information - Visit Number (Event A45)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

A move has been done at the visit identifier level. That is, a _PV1-19 - Visit Number_ or _PV1-50 - Alternate Visit ID_ associated with one account identifier (_PID-18 - Patient Account Number_) has been moved to another account identifier.

An A45 event is used to signal a move of records identified by the _MRG-5 - Prior Visit Number_ or the _MRG-6 - Prior Alternate Visit ID_ from the "incorrect source account identifier" identified in the MRG segment (_MRG-3 - Prior Patient Account Number_) to the "correct target account identifier" identified in the PID segment (_PID-18 - Patient Account Number_).

This event and the message syntax do allow for the specification of "new identifiers" (_PV1-19 - Visit Number_, or _PV1-50 - Alternate Visit ID_), which may be application and/or implementation-specific and therefore require site negotiation.

All of the identifiers superior to the visit number or alternate visit ID should be valued in both the MRG segment and the PID segments. In this message, the account number and _PID-3 - Patient Identifier List_ are superior to the visit number and alternate visit ID.

See sections link:#merging-patientperson-information[_3.6.2_&#44;] "link:#merging-patientperson-information[_Merging patient/person information_]," and link:#move[_3.6.2.1.3_], "link:#move[_Move_]," for a discussion of issues related to the implementation of move messages. The fields included when this message is sent should be the fields pertinent to communicate this event. When demographic data in other fields change, it is recommended that the A08 (update patient information) event be used in conjunction with this message. However, all PID data associated with the "correct target visit ID" are treated as updated information.

[tabset]
A45








