= Message - A49 Change Patient Account Number 
:v291_section: "3.3.49"
:v2_section_name: "ADT/ACK - Change Patient Account Number (Event A49)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

A change has been done at the account identifier level. That is, a PID-18 - patient account number has been found to be incorrect and has been changed.

An A49 event is used to signal a change of an incorrectly assigned account number value. The "incorrect source account number" value is stored in the MRG segment (_MRG-3 - Prior Patient Account Number_) and is to be changed to the "correct target account number" value stored in the PID segment (_PID-18 - Patient Account Number_).

The patient account identifier involved in identifying the account may or may not have visits. An A49 (change patient account number) event is intended for changing the value of the account identifier without affecting other subordinate identifiers. Any other subordinate identifiers that were previously associated with the "incorrect source account number" are now associated with the "correct target account number". Specification of these other subordinate identifiers is not required.

This event and the message syntax do, however, allow for the specification of "new subordinate identifiers" (in addition to the _PID-18 - Patient Account Number Identifier_). For those environments that may require changes to these other subordinate identifiers because of this A49 (change patient account number) event, it is required that the old and new identifiers be a "tightly coupled" pair.

Each superior identifier associated with this account identifier level, i.e. the PID-3/MRG-1 should have the same value in both the PID and MRG segments.

See sections link:#merging-patientperson-information[_3.6.2_&#44;] "link:#merging-patientperson-information[_Merging patient/person information_]," and link:#change-identifier[_3.6.2.1.4_], "link:#change-identifier[_Change identifier_]," for a discussion of issues related to the implementation of change messages.

The fields included when this message is sent should be the fields pertinent to communicate this event. When demographic data in other fields change, it is recommended that the A08 (update patient information) event be used in conjunction with this message.

[message_structure-table]

[ack_chor-table]

[ack_message_structure-table]

[ack_chor-table]

