= Message - A50 Change Visit Number
:v291_section: "3.3.50"
:v2_section_name: "ADT/ACK - Change Visit Number (Event A50)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

A change has been done at the visit identifier level. That is, a _PV1-19 - Visit Number_ has been found to be incorrect and has been changed.

An A50 event is used to signal a change of an incorrectly assigned visit number value. The "incorrect source visit number" value is stored in the MRG segment (_MRG-5 - Prior Visit Number_) and is to be changed to the "correct target visit number" value stored in the PV1 segment (_PV1-19 - Visit Number_).

Each superior identifier associated with this visit number identifier level, i.e. PID-3/MRG-1 and PID-18/MRG-3 should have the same value in both the PID and MRG segments.

See sections link:#merging-patientperson-information[_3.6.2_&#44;] "link:#merging-patientperson-information[_Merging patient/person information_]," and link:#change-identifier[_3.6.2.1.4_], "link:#change-identifier[_Change identifier_]," for a discussion of issues related to the implementation of change messages.

The fields included when this message is sent should be the fields pertinent to communicate this event. When demographic data in other fields change, it is recommended that the A08 (update patient information) event be used in conjunction with this message.

[tabset]
A50








