= Message - A54 Change Attending Doctor
:v291_section: "3.3.54"
:v2_section_name: "ADT/ACK - Change Attending Doctor (Event A54)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

An A54 event is issued as a result of a change in the attending doctor responsible for the treatment of a patient.

When other important fields change, it is recommended that the A08 (update patient information) event be used in addition.

The new attending doctor of the patient should appear in the _PV1-7 - Attending Doctor_. For example, an A54 event can be used to notify the billing system that doctors' fees should be billed to the new doctor starting from the timestamp in the message.

The ROL - Role Segment was used in this message to communicate providers not specified elsewhere. As of v2.9, this has been deprecated in preference to the PRT segment as a more robust and flexible method of conveying participation. Hereafter, instructions for the PRT segment should apply, using the PRT segment. Person level providers with an ongoing relationship are reported in the PRT segment following the PID/PD1 segments. Providers corresponding to the PV1 data are reported in the PRT segment following the PV1/PV2 segments. Providers related to a specific procedure are reported in the PRT segment following the PR1 segment. Providers related to a specific insurance are reported in the PRT segment following the IN1/IN2/IN3 segments.

To communicate the begin and end date of the attending, referring, or admitting doctor, use the _PRT-11 - Begin Date/Time_ and the _PRT-12 - End Date/time_ in the PRT segment, with the applicable _PRT-4 – Role of Participation_. Refer to Chapter 7 for the definition of the PRT segment. Use "UP" in _PRT-2 - Action Code_.

[tabset]



[ack_message_structure-table]



