=== EKG Results Reporting
[v291_section="7.5.6"]

Suppose an order has been placed to the EKG system for three EKGs to be performed on successive days. These results can be reported in various ways.

{empty}1) The EKG application needs to communicate to anyone the results of the 1st EKG:

ORU message:

MSH|...<cr>

PID|...<cr>

Order record for EKG

[er7]
OBR|1|P8753^OE|EK5230^EKG|8601-7^EKG impression^LN|||198703290800|||401

0^INTERN^IRVING^I^^^MD^L|...<cr>

Two interpretation records for EKG

[er7]
OBX|1|CWE|8601-7^EKG impression^LN|1|^Sinus bradycardia|||A|||F|...<cr>
[er7]
OBX|2|CWE|8601-7^EKG impression^LN |2|^Occasional PVCs|||A|||F|...<cr>

Four numeric results for EKG

[er7]
OBX|3|NM|8897-1^QRS COMPLEX RATE ^LN|
[er7]
|80|/min|60-100|||||F|...<cr>
[er7]
OBX|4|NM|8894-8^PULSE RATE^LN||80|/min
[er7]
|60-100||||F|...<cr>
[er7]
OBX|5|NM|8633-0^QRS DURATION ^LN||.08|msec
[er7]
|.06-.10||||F|...<cr>
[er7]
OBX|6|NM|8625-6^P-R INTERVAL ^LN||.22|msec
[er7]
|.18-.22||||F|...<cr>

• Notice that this report is without reference to the original order.

• No ORC is required because the identifying Fillers Order Number (and other ORC fields) is carried in the OBR segment.

• The EKG application needs to communicate to anyone the original order information, the details of the child orders, the fact of the child spin off, and the results of all three EKGs:

ORU message:

MSH|...<cr>

PID|...<cr>

[er7]
ORC|PA|A226677^OE|89‑450^EKG|...<cr> // original order's ORC.
[er7]
OBR|1|||8601-7^EKG REPORT|...<cr> // original order segment
[er7]
ORC|CH|A226677^OE|89-451^EKG|...<cr> // 1st child ORC.
[er7]
OBR|1|||8601-7^EKG REPORT|...<cr> // 1st EKG child OBR.
[er7]
OBX|1|ST|...<cr> // 1st EKG report
[er7]
OBX|2|ST|...<cr>

...

[er7]
OBX|14|FT|...<cr>
[er7]
ORC|CH|A226677^OE|89-452^EKG|...<cr> // 2nd child ORC.
[er7]
OBR|1|||8601-7^EKG REPORT|...<cr> // 2nd EKG child OBR.
[er7]
OBX|1|ST|...<cr> // 2nd EKG report
[er7]
OBX|2|ST|...<cr>

...

[er7]
OBX|14|FT|...<cr>
[er7]
ORC|CH|A226677^OE|89-453^EKG|...<cr> // 3rd child ORC.
[er7]
OBR|1|||8601-7^EKG REPORT|...<cr> // 3rd EKG child OBR.
[er7]
OBX|1|ST|...<cr> // 3rd EKG report
[er7]
OBX|2|ST|...<cr>

...

[er7]
OBX|14|FT|...<cr>

... // Other parts of message might follow.

In this case, we are transmitting the information about the fact of child spin off, the original order and the results all at the same time. Thus, this form of the ORU message reports not only the results of an order, but all of its associated ordering information including the original OBR for three EKGs that was replaced by three separate OBR EKG segments.

