= Message – Unsolicited Order Oriented Observation
:v291_section: "7.3.10"
:v2_section_name: "OUL – Unsolicited Order Oriented Observation Message (Event R24)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

This message was designed to accommodate multi-specimen oriented testing. It should be applicable to, e.g., laboratory automation systems requiring container.

Generally this construct allows *transfer of multiple results, each one related to none, one or more specific containers with one or more specimens from a patient.* (Example: Creatinine Clearance result with detailed information about the urine and serum specimens and their containers.)

In addition to the patient results themselves it permits the communication of the following kinds of information:

• Analysis results of a non patient related sample (e.g., environmental) – patient related segments (e.g., PID, PD1, PV1, PV2) are optional.

• Analysis results to a particular container with QC sample and the lot and manufacturer information about this sample (SAC-INV segments).

• Basic identification data (lot, manufacturer, etc.) of the reagents and other substances involved in the generation of analysis results (TCD-SID segments).

Refer to Chapter 13 Laboratory Automation for additional examples of usage of SAC.

The Device segment (DEV) provides additional device information for a device referenced in one or more of the PRT segments in the message (using PRT-10 Participation Device to match DEV-2 Unique Device Identifier or PRT-22 Participation Device Type using DEV-3 Device Type).

[tabset]
R24



