=== Acknowledgment Choreography
[v291_section="2.4.6"]

Acknowledgment Choreography is defined as the definition of the acknowledgments to be expected for a given trigger event. It is required to document the expected acknowledgment based on the values in link:#_MSH-15___Accept Acknowledgment Type[MSH-15] and link:#_MSH-16___Application Acknowledgment[MSH-16].

As of V2.9, all chapters SHALL include in their trigger event definitions the acknowledgment choreography.

The first row SHALL contain the words "Acknowledgment Choreography". The second row SHALL contain the message definition being described. When multiple message definitions have the same response in the same chapter all of the message pairs MAY be listed in the second row.

The values rows MSH-15 and MSH-16 are extracted from the valid values for the field.

The Application ACK row SHOULD contain the message expected in reponse to the processing of the message named in third row containing the value(s) for MSH-16 in that column.

[ack_chor-table]

For proper formatting please consult the styleguide.

