// FIXME note that this document uses example captions in the Examples section.  This may not have been adopted as standard practice...
:example-caption!:

= Dietary

== Introduction
[v291_section="4.7"]

A diet office needs to receive specific information, the most important being the diet order itself. Diet restrictions (often called diet codes) are the basic building blocks of a diet order. The diet order segments may be sent as part of the ORM and ORR message structure to support backwards compatibility, or may be sent as part of the following dedicated message structures.

== Technical Specs

xref:technical_specs/O03.adoc[Message O03 - Dietary Order]

== Examples

[v291_section="4.9.1"]
=== Typical progression of orders for a surgery patient 
 
.First order:
[er7]
MSH|...<cr>
PID|...<cr>
ORC|NW|1235^NURS|||||^^^199108021700||200608021200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>
ODS|D||321^DB15^99DO3|...<cr>
ODS|D||322^NA2GM^99DO3|<cr>

.Hold first order:
[er7]
MSH|...<cr>
PID|...<cr>
ORC|HD|1235^NURS|||||^^^200608031700||200608031200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>

.NPO order with guest tray:
[er7]
MSH|...<cr>
PID|...<cr>
ORC|NW|1236^NURS|||||^^^200608031700||200608031200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>
ODS|D||323^NPO^99DO3|...<cr>
ORC|NW|1244^NURS|||||^^^200608031700||200608031200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>
ODT|GUEST^Guest tray^HL70160|5^^99CBD|...<cr>

.Clear liquid with guest tray:
[er7]
MSH|...<cr>
PID|...<cr>
ORC|DC|1236^NURS|||||^^^200608041700||200608041200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>
ORC|NW|1237^NURS|||||^^^200608041700||200608041200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>
ODS|D||321^DB15^99DO3|...<cr>
ODS|D||322^NA2GM^99DO3|...<cr>
ODS|D||324^CLRLIQ^99DO3|...<cr>
ORC|NW|1245^NURS|||||^^^200608041700||200608041200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>
ODT|GUEST^Guest tray^HL70160|5^^99CBD|...<cr>

.Full liquid with guest tray:
[er7]
MSH|...<cr>
PID|...<cr>
ORC|DC|1237^NURS|||||^^^200608051700||200608051200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>
ORC|NW|1238^NURS|||||^^^200608051700||200608051200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>
ODS|D||321^DB15^99DO3|...<cr>
ODS|D||322^NA2GM^99DO3|...<cr>
ODS|D||325^FULLIQ^99DO3|...<cr>
ORC|NW|1246^NURS|||||^^^200608051700||200608051200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>
ODT|GUEST^Guest tray^HL70160|3^^99CBD|...<cr>

.Release hold on previous order and give discharge message:
[er7]
MSH|...<cr>
PID|...<cr>
ORC|DC|1238^NURS|||||^^^200608061700||200608061200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>
ORC|RL|1235^NURS|||||^^^200608061700||200608061200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>
ORC|NW|1247^NURS|||||^^^200608061700||200608061200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>
ODT|MSG^Tray message only^HL70160|5^^99CBD|You Will Be Leaving Tomorrow|...<cr>

=== Complex order
[v291_section="4.9.2"]

Basic diet: high protein, low fat. Supplements are ice cream at service period 4 and a half ham sandwich at service period 6. There are also tray orders for early service period 1, late service period 3, and guest tray at dinner.

[er7]
MSH|...<cr>
PID|...<cr>
ORC|NW|1234^NURS|||||^^^200608021700||200608021200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>
ODS|D||011^HIPRO100^99FD1|...<cr>
ODS|D||123^LOFAT20^99FD1|...<cr>
ODS|S|4|119^ICE CREAM^99FD8|...<cr>
ODS|S|6|320^1/2 HAM SANDWICH^99FD8|...<cr>
ORC|NW|1244^NURS|||||^^^200608031700||200608031200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>
ODT|EARLY^Early tray^HL70160|1^^99CBD|...<cr>
ORC|NW|1245^NURS|||||^^^200608031700||200608031200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>
ODT|LATE^Late tray^HL70160|3^^99CBD|...<cr>
ORC|NW|1246^NURS|||||^^^200608031700||200608031200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>
ODT|GUEST^Guest tray^HL70160|5^DINNER^99CBD|...<cr>

=== Tube feeding
[v291_section="4.9.3"]

This order specifies Similac with MCT oil and polycose additives.

[er7]
MSH|...<cr>
PID|...<cr>
ORC|NW|1232^NURS|||||60^Q3H^^200608021700||200608021200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>
ODS|D||010^SIMILAC^99DO1|...<cr>
ODS|D||011^MCT^99DO1|...<cr>
ODS|D||012^POLYCOSE^99DO1|...<cr>

=== Patient preference
[v291_section="4.9.4"]

This order specifies that the patient is a vegetarian.

[er7]
MSH|...<cr>
PID|...<cr>
ORC|NW|1232^NURS|||||60^Q3H^^200608021700||200608021200|333-77-7777^COMRAD^CONNOR^C|999-99-9999^VERIFY^VIRGIL^V|...<cr>
ODS|D||123^LOFAT20^99FD1|...<cr>
ODS|S|4|119^ICE CREAM^99FD8|...<cr>
ODS|P||^VEGETARIAN|...<cr>
