==== Example message
[v291_section="8.6.2.1"]

The initiating system constructs an MFN^M14 message. In this example, the message contains site-defined "Z" segments. The following message is sent to the responding system:

[er7]
MSH|^~\&|HL7REG|UH|HL7LAB|CH|200106290544||MFN^M14^MFN_Z99|MSGID001|P|2.9

[er7]
MFI|HL70006^RELIGION^HL70175||UPD|||AL

[er7]
MFE|MAD|6772331|200106290500|BUD^Buddhist^HL70006|CWE

[er7]
ZL7|BUD^Buddhist^HL70006|3

[er7]
MFE|MAD|6772332|200106290500|BOT^Buddhist: Other^HL70006|CWE

[er7]
ZL7|BOT^Buddhist: Other^HL70006|4


The responder receives the message and performs necessary validation on the message. In this example, it determines the message just received is acceptable for processing. The following MFK^M14 message is constructed by the responder and sent to the initiating system to indicate acknowledgment of the MFN^M14 message:

[er7]
MSH|^~\&|HL7LAB|CH|HL7REG|UH|200106290545||MFK^M14^MFK_M01|MSGID99001|P|2.9

[er7]
MSA|AA|MSGID001

[er7]
MFI|HL70006^RELIGION^HL70175||UPD|||AL

[er7]
MFA|MAD|6772331|200106290545|S|BUD^Buddhist^HL70006|CWE

[er7]
MFA|MAD|6772332|200106290545|S|BOT^Buddhist: Other^HL70006|CWE


[NOTE]
that _MSA-1 - Acknowledgment Code_ contains 'AA' to indicate the message was received and processed successfully. This value could also have been 'AE' or 'AR' to indicate the message was received but not processed successfully. _MSA-2 - Message Control ID_ contains the value from _MSH-10 - Message Control ID_ in the initiating MFN^M14 message (MSGID001) to link the acknowledgment response to the initiating message.

