==== Example of interactive continuation protocol
[v291_section="5.6.3.3"]

The user wishes to know all the medications dispensed for the period between January 1, 1998, and December 31, 1999, for the patient whose medical record number is "555444222111". The Client submits the following query and invokes the interactive continuation protocol. Note that the quantity has been limited to 8 lines.

[er7]
MSH|^~\&|PCR|Gen Hosp|IE||200009171400-0800||QBP^Q41^QBP_Q15|8699|P|2.8||||||||

[er7]
QPD|Q41^DispenseHistory^HL7nnnn|Q001|555444222111^^^MPI ^MR||19980101|19991231|

[er7]
RCP|I|8^LI|


The pharmacy system identifies medical record number "555444222111" as belonging to Adam Everyman and locates 7 prescription dispenses meeting the criteria. As shown in the following response, eight lines of data are returned as requested. The response ends with a DSC segment showing the continuation pointer and the indication that this is a logical breaking point.

[er7]
MSH|^~\&|PIMS|Gen Hosp|PCR||200009171401-0800||RDY^R41^RDY_K15|8858|P|2.8||||||||

[er7]
MSA|AA|8699|

[er7]
QAK|Q001|OK|Q41^DispenseHistory^HL7nnnn|^8

[er7]
QPD|Q41^DispenseHistory^HL7nnnn|Q001|555444222111^^^MPI^MR||19980101|19991231|

[er7]
DSP||| GENERAL HOSPITAL – PHARMACY DEPARTMENT DATE:09-17-00

[er7]
DSP||| DISPENSE HISTORY REPORT PAGE 1

[er7]
DSP|||MRN Patient Name MEDICATION DISPENSED DISP-DATE

[er7]
DSP|||555444222111 Everyman,Adam VERAPAMIL HCL 120 mg TAB 10/12/1999

[er7]
DSP|||555444222111 Everyman,Adam VERAPAMIL HCL ER TAB 180MG 09/21/1999

[er7]
DSP|||555444222111 Everyman,Adam BACLOFEN 10MG TABS 08/22/1999

[er7]
DSP|||555444222111 Everyman,Adam THEOPHYLLINE 80MG/15ML SOL 05/29/1999

[er7]
DSP||| << END OF Screen>>

[er7]
DSC|77|I|


The Client wishes to receive another payload. [multiblock footnote omitted]

[er7]
MSH|^~\&|PCR|Gen Hosp|IE||199811201405-0800||QBP^Q41^QBP_Q15|8890|P|2.8||||||||
[er7]
QPD|Q41^DispenseHistory^HL7nnnn|Q001|555444222111^^^MPI^MR||19980101|19991231|
[er7]
RCP|I|8^LI|
[er7]
DSC|77|I|

The Server returns the next payload and indicates in _QAK-4-Hit count_ that this is the last of the data..

[er7]
MSH|^~\&|PIMS|Gen Hosp|PCR||199811201407-0800||RDY^K15^RDY_K15|8898|P|2.8||||||||

[er7]
MSA|AA|8890|

[er7]
QAK|Q001|OK|Q41^DispenseHistory^HL7nnnn|^7^^Y|

[er7]
QPD|Q41^DispenseHistory^HL7nnnn|Q001|555444222111^^^MPI^MR||19980101|19991231|

[er7]
DSP||| GENERAL HOSPITAL – PHARMACY DEPARTMENT DATE:09-17-99

[er7]
DSP||| DISPENSE HISTORY REPORT PAGE 1

[er7]
DSP|||MRN Patient Name MEDICATION DISPENSED DISP-DATE

[er7]
DSP|||555444222111 Everyman,Adam VERAPAMIL HCL 120 mg TAB 05/29/1998

[er7]
DSP|||555444222111 Everyman,Adam VERAPAMIL HCL ER TAB 180MG 04/21/1998

[er7]
DSP|||555444222111 Everyman,Adam BACLOFEN 10MG TABS 04/22/1998

[er7]
DSP||| << END OF REPORT>>


The query/response is now completed.

