=== Query using QSC variant (QBP) / display response (RDY)
[v291_section="5.9.6"]

The user wishes to know all the medications ever dispensed for the patient whose medical record number is "555444222111" prescribed by Dr Lister (provider number 99). The following message is generated. (Note the similarity between the QPD segment here and that used in the query in Section 5.8.4.)

[er7]
MSH|^~\&|PCR|Gen Hosp|PIMS||199811201300-0800||QBP^Z79^QBP_Q15|8698|P|2.8||||||||

[er7]
QPD|Z79^Dispense Information^HL7nnnn|Q503 |PID.3^EQ^55544422211^AND|ORC.1^EQ^RE^AND|ORC.12.1^EQ^99

[er7]
RCP|I|999^RD|


The pharmacy system identifies medical record number "555444222111" as belonging to Adam Everyman and locates 2 prescription dispenses as prescribed by Dr. Lister. The response is clearly different than the response to the first query.

[er7]
MSH|^~\&|PIMS|Gen Hosp|PCR||199811201300-0800||RDY^Z80^RDY_K15|8857|P|2.8||||||||

[er7]
MSA|AA|8698|

[er7]
QAK|Q003|OK|Z79^Dispense Information^HL7nnnn|2

[er7]
QPD|Z79^Dispense Information^HL7nnnn|Q503 |@PID.3^EQ^55544422211^AND~ORC.1^EQ^RE^AND~@RXD.3^GE^199711200000-0800^AND~@RXD.3^LE^199811200000-0800

[er7]
DSP||| GENERAL HOSPITAL – PHARMACY DEPARTMENT DATE:09-17-99

[er7]
DSP||| DISPENSE HISTORY REPORT PAGE 1

[er7]
DSP|||MRN Patient Name MEDICATION DISPENSED DISP-DATE

[er7]
DSP|||555444222111 Everyman,Adam VERAPAMIL HCL 120 mg TAB 05/29/1998

[er7]
DSP|||555444222111 Everyman,Adam THEOPHYLLINE 80MG/15ML SOL 10/12/1998

[er7]
DSP||| << END OF REPORT >>


