= Message – Unsolicited Patient-Device Association Observation
:v291_section: "7.3.15"
:v2_section_name: "ORU – Unsolicited Patient-Device Association Observation Message (Event R43)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

The R43 trigger event is used for observation reports that indicate the association of one patient to one or more health care devices. This includes both patient-device association as well as disassociation when a device is removed from active use with a patient. Other messages may be utilized for this purpose (e.g., ADT); however, this message was chosen given the general use of ORU-style messages to communicate device data, including unique device identifiers (e.g., PRT-10 and UDI components), and the possible need to include additional device data such as hardware / software configuration. The R43 trigger provides indication of the specialized usage of this message. Note that OBX-3 Observation Identifier, PRT-4 Participation, and OBX-11 Observation Result Status represent the purpose of the association of the device and the status of that association as further defined through the appropriate implementation guides and/or profiles.

Use cases that this message supports include:

• Simple patient-device association where a system that integrates a bar code or RFID reader is used to capture patient and device identifiers at the point of care and then communicate those to other devices and systems that process device data associated with the same patient.

• When one or more devices are no longer associated with a patient, this message can be used to communicate this change of status

• Systems may not only perform the identifier acquisition from patients and devices, but may also authenticate the identifiers and support cross-referencing (e.g., when there are multiple patient identifiers)

In the latter use case, this message can be used to establish a “source of truth” for patient-device associations. There are many systems in and supportive of the point of care that make associations between patients and health care devices, all of which need to be coordinated to ensure there are no mis-matches between information sources and the patients to which they are associated.

The message shall identify a patient with optional location information, and one or more device observations, each including a unique device identifier along with an indication of whether the device is being associated or disassociated with the specified patient. In addition, a single observation can be specified to disassociate all devices for a given patient.

[tabset]



