=== Establishing a subscription
[v291_section="5.7.4"]

To establish the subscription to see lab results for two patients, an authorized Subscriber (e.g., CommunityWest) would send a query message with event code Q99:

[er7]
MSH|^~\&|CPR|COMWEST|PS^LAB||||QSB^Q99^QSB_Q16|8888|P|2.8|

[er7]
QPD|Q99^ORU_Subscription^HL7nnnn|Q0044|1234^^^MPI^MR~4567^^^MPI^MR|

[er7]
RCP||||||N|


As results are generated by the Lab, they are all sent to the archive. In addition, the Lab has a list of all subscription requests (such as the message, above). For each message, it checks the query filters associated with the subscription against the message being considered. If the message matches the query, it is sent to the recipient.

For example, a hit on patient 4567 would result in the message:

[er7]
MSH|^~\&|PS^LAB||CPR|COMWEST||||ORU^R01^ORU_R01|4409|P|2.8|
[er7]
PID|||4567^^^MPI^MR|....

OBR|....

OBX|...

[NOTE]
The result message has message type ORU^R01^ORU_R01 (as specified by the Query Profile).

