= TODO and Questions

This file contains a TODO list for tasks related to setting up the v2+ editing environment.  It also includes a list of related questions.

== TODO

*	In Chapter 15, for QBP/RSP, the usage of "Conformance Statement" in the opening bit of the technical_specs file is probably not correct. We should review

* Figure out a strategy for dealing with Glossary terms
** Combine them? Leave them in Context? Make a decision based on the specificity of the term?
** Make the first reference in text a hyperlink which goes to a glossary
*** Editors tag these with GLOSSARY so that we can find them later

* Confirm the addition of the Consent content from Chapter 9 to the Administrative Domain
** This is OK

*	Review remaining TBD sections
**	7.17+ - Units lists (tables)
**	9.4.1 - Consent 9 (see topic above)
**	5.10+ (5.9 in v2.9.1) – Superseded stuff
**	5.11 (5.10 in v2.9.1) – outstanding issues (move to Jira if still an issue??)

* Decide on where to put Item Inventory and Master File content
** Moved to content from Chapter 17 to Chapter 8

* Review the "rules" in Chapter 12 relative to general guidance in Chapter 2

* Review content of the Communicating Collaborative Care of a Patient section of the Referrals domain for wording about using segments in ways they weren't intended

* Decide on section numbering (for example compare Scheduling with Referrals)

* Fix the typos identified in https://jira.hl7.org/browse/V2-25565

== Questions

* Should "domain" be restricted to just the high-level groups (administrative, clinical, erp, financial and technical) with "topic" or some other word used for the next level (registration, scheduling, materials management, immunization)? Or is everything OK to describe as a "domain"? "Transaction set" is also used a lot in a variety of chapters.
** We decided on "topic" as the word

* Several chapters have text similar to the following. Does this need to be in every chapter?
** This domain defines the transactions at the seventh level, that is, the abstract message. Various schemes are used to generate the actual characters that comprise the messages according to the communication environment. The HL7 Encoding Rules will be used where there is not a complete Presentation Layer. This is described in Chapter 1, "Relationship to Other Protocols." The examples included in this domain were constructed using the HL7 Encoding Rules.
** This can be removed and only live in Chapter 1 (Introduction)

* Should the links to tech_specs really not include the event(s) identifiers??

* Are we updating dates in example messages?
** Yes - dates and general best practices

* Chapter 6 recommends Z-segments for state-specific requirements. Can this be removed?
** Yes

* The P03 (Common Order Group) and P11 message definitions in Chapter 6 contain footnotes and notes. How should these be rendered?

* Can we convert footnotes to regular text?
** check with Lynn to see if these are normative now

*	Should Patient Care (Chapter 12) be updated from "patient care" to "problem-oriented records" to be more specific?
**	Something similar seems to have been done for Medical Records (Chapter 9)/Document Management
** Yes, rename

* How are we formatting references to segments, fields, components and subcomponents
** OBX segment  OBX - Observation Segment
** PID-3  PID-3 - Patient Identifier
** Look at the existing style guide for v2

* Are we removing text referencing "future plans" for various content (such as in Chapter 9)
** Remove and clean up

* Where does the Chapter 1 stuff go?
** Into an Introduction Section

* Do we really need chapter 5?

* What should the header for the individual Data Type pages look like?
** (AD) Data Type - address
** AD - Address
** Address (AD) Data Type
** DECISION: use AD - Address

* In general, do statements like "Refer to User-defined Table 0305 - Person location type for suggested values." mean anything when the user defined table is empty? Can these be removed as part of the terminology transition away from tables?
