= Message - I16 Collaborative Care Referral
:v291_section: "11.6.3"
:v2_section_name: "CCR/ACK – Collaborative Care Referral (Event I16)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

This event triggers a message to be sent from one healthcare provider to another regarding a specific patient or group of patients. The intent is to create a collaborative relationship between the referring provider, the referred to provider or providers and the patient or patients, for the shared care of the patient or patients. The collaborative care referral may contain specific clinical orders, patient demographic information, a full history of appointments, specific medical procedures that have been performed, a full clinical history, an administrative history of patient visits, a full medication history, all relevant problems, pathways and goal. The collaborative care referral message definitely implies intent to share, or transfer some, or all, of the care of the patient to the referred to provider or providers. Whilst the acknowledgment is a simple ACK message, the expectation is that the referred to provider(s) will send back a CCU – Asynchronous Collaborative Care Update at a later time to indicate acceptance or rejection of the referral.

[tabset]
I16
