= Message - I17 Modify Collaborative Care Referral
:v291_section: "11.6.4"
:v2_section_name: "CCR/ACK – Modify Collaborative Care Referral (Event I17)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

This event triggers a message to be sent from one healthcare provider to another regarding changes to an existing Collaborative Care Referral. Changes may include additional instructions from the referring provider, additional clinical orders, additional clinical history, additional patient visits, additional medication history, or modifications to the problems, goals and/or pathways. The collaborative care referral may contain specific clinical orders, patient demographic information, a full history of appointments, specific medical procedures that have been performed, a full clinical history, an administrative history of patient visits, a full medication history, all relevant problems, pathways and goal. The collaborative care referral message definitely implies intent to share, or transfer some, or all, of the care of the patient to the referred to provider or providers. Whilst the acknowledgment is a simple ACK message, the expectation is that the referred to provider(s) will send back a CCU – Asynchronous Collaborative Care Update at a later time to indicate acceptance or rejection of the modifications.

[tabset]
I16

FIXME - confirm that the I16 message tabset is OK for events I16 through I18
