= Message - I18 Cancel Collaborative Care Referral
:v291_section: "11.6.5"
:v2_section_name: "CCR/ACK – Cancel Collaborative Care Referral (Event I18)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

This event triggers a message to be sent from one healthcare provider to another canceling an existing Collaborative Care Referral. A previous Collaborative Care Referral may have been made in error, or perhaps the cancellation has come from the patient. The collaborative care referral may contain specific clinical orders, patient demographic information, a full history of appointments, specific medical procedures that have been performed, a full clinical history, an administrative history of patient visits, a full medication history, all relevant problems, pathways and goal. The collaborative care referral message definitely implies intent to share, or transfer some, or all, of the care of the patient to the referred to provider or providers. Whilst the acknowledgment is a simple ACK message, the expectation is that the referred to provider(s) will send back a CCU – Asynchronous Collaborative Care Update at a later time to indicate cancellation of the Collaborative Care Referral.

[tabset]
I16
