= Message - S29 Request Sterilization Lot Deletion
:v291_section: "17.6.2"
:v2_section_name: "SLR/ACK/SLS - Request Sterilization Lot Deletion (Event S29)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

A request sterilization lot deletion is sent by the placer application to the filler application to request that a lot that had been created in error be removed from the system. A delete trigger event differs from a cancel trigger event in that a delete acts to remove an error, whereas a cancel acts to prevent a valid request from occurring. If it is successful, an application acknowledgment is returned.

The delete trigger event should be implemented with careful forethought, as it typically has different effects and repercussions in various applications. In some applications, a delete event cannot be undone. This means that if a delete transaction was sent erroneously, recovery will be difficult or impossible. In other applications, a delete transaction will not result in the physical deletion of the record(s), but will set a status or a flag. In these cases, the filler and/or placer appointment identifiers (the numbers or codes that uniquely identify the sterilization lot or request to the placer and filler applications) probably cannot be reused. Since an application may maintain a record of deleted sterilization lots, the reuse of an identifier may cause a conflict in the applications' processing of transactions.

[message_structure-table]

[ack_chor-table]

[ack_message_structure-table]

[ack_chor-table]

[message_structure-table]

[ack_chor-table]

