= (CNE) Data Type - coded with no exceptions
:v291_section: 2A.2.8
:v2type: 'Data Type'
:code: CNE
:name: coded with no exceptions
:primitive: false
:target-element: CNE
:generated: Thu, 19 Sep 2024 15:32:55 -0600

As of v2.7 a third tuple, formerly known as triplet, has been added to the CNE data type. Additionally, 3 new components were added to each tuple such that each tuple now has a total of 7 components. The Original Text component applies to the CNE as a whole.

[NOTE]
The Vocabulary TC is the steward of the CNE data type.

[datatype-definition]
Specifies a coded element and its associated detail. The CNE data type is used when a required or mandatory coded field is needed. The specified HL7 table or imported or externally defined coding system must be used and may not be extended with local values. Text may not replace the code. A CNE field must have an HL7 defined or external table associated with it. A CNE field may be context sensitive such that a choice of explicit coding systems might be designated. This allows for realm and other types of specificity. Every effort will be made to enumerate the valid coding system(s) to be specified in the 3rd component, however, the standards body realizes that this is impossible to fully enumerate.

[NOTE]
The presence of two sets of equivalent codes in this data type is semantically different from a repetition of a CNE-type field. With repetition, several distinct codes (with distinct meanings) may be transmitted.

[example]
1: The drug must be coded and must be taken from the specified coding system. The coding system is an external coding system. Example is derived from _FT1-26_.

|0006-0106-58\^Prinivil 10mg oral tablet^NDC|

[example]
2: Consent mode must be coded and must be taken from the specified coding system. The coding system is an HL7 code table. Example is taken from _CON-10_.

|V\^Verbal^HL70497\^^\^^2.8|

include::CNE-components/CNE-1.adoc[]

include::CNE-components/CNE-2.adoc[]

include::CNE-components/CNE-3.adoc[]

include::CNE-components/CNE-4.adoc[]

include::CNE-components/CNE-5.adoc[]

include::CNE-components/CNE-6.adoc[]

include::CNE-components/CNE-7.adoc[]

include::CNE-components/CNE-8.adoc[]

include::CNE-components/CNE-9.adoc[]

include::CNE-components/CNE-10.adoc[]

include::CNE-components/CNE-11.adoc[]

include::CNE-components/CNE-12.adoc[]

include::CNE-components/CNE-13.adoc[]

include::CNE-components/CNE-14.adoc[]

include::CNE-components/CNE-15.adoc[]

include::CNE-components/CNE-16.adoc[]

include::CNE-components/CNE-17.adoc[]

include::CNE-components/CNE-18.adoc[]

include::CNE-components/CNE-19.adoc[]

include::CNE-components/CNE-20.adoc[]

include::CNE-components/CNE-21.adoc[]

include::CNE-components/CNE-22.adoc[]

