= (CWE) Data Type - coded with exceptions
:v291_section: 2A.2.13
:v2type: 'Data Type'
:code: CWE
:name: coded with exceptions
:primitive: false
:generated: Thu, 19 Sep 2024 15:32:55 -0600

As of v2.7 a third tuple, formerly known as triplet, has been added to the CWE data type. Additionally, 3 new components were added to each tuple such that each tuple now has a total of 7 components. The Original Text component applies to the CWE as a whole.

[NOTE]
The Vocabulary TC is the steward of the CWE data type.

[datatype-definition]
Specifies a coded element and its associated detail. The CWE data type is used when 1) more than one table may be applicable *or* 2) the specified HL7 or externally defined table may be extended with local values *or* 3) when text is in place, the code may be omitted.

The presence of two sets of equivalent codes in this data type is semantically different from a repetition of a CWE-type field. With repetition, several distinct codes (with distinct meanings) may be transmitted.

[#CWE_UsageNote .anchor]##*Usage Notes:* The CWE data type should be used for coded fields with one or more of the following characteristics:

• The identifier code (CWE.1) component is optional

• The set of allowable values from which the identifier code is drawn may be extended on a site-specific basis

• An exception identifier code may be encountered; that is, a code that is not defined in the value set (either model or site-extended).

This is in contrast to the CNE data type, which requires a code from a non-extendable value set be sent in the identifier code component (CNE.1) in all cases (except, of course, if the entire field is empty and defined as optional at the segment level).

.The rules for populating CWE components are governed by the status of the identifier code:
[width="100%",cols="27%,24%,25%,24%",]
|===
|*Identifier Code Status* |*Identifier Code (CWE.1)* |*Descriptive Text (CWE.2)* |*Coding System (CWE.3)*
|Contained in model value set |Populated |May be populated |Must be populated with model coding system, or (not recommended) site-specific coding system that is a superset containing model values.
|Contained in site-specific extensions to model value set |Populated |May be populated |Site-specific coding system.
|Contained in neither model nor extended value sets |Not populated |May be populated with the identifier code, free-text description, or a concatenation of the two. Should be human interpretable. |Must not be populated.
|Not supplied; but descriptive text is supplied. |Not populated |May be populated with descriptive text. |Must not be populated.
|===

As an example, consider “currency” codes where:

• The model values are defined by the ISO 4217 value set,

• The value set is extended on site to include the code HL7 – “HL7 Drink Ticket”, and

• The data entry screen on the sending system does not enforce any edits for the currency code.

.And so the value set used on site is:
[width="100%",cols="33%,20%,47%",]
|===
|Identifier Code Status |Identifier Code |Descriptive Text
|Model values from ISO 4217 external table |AED |United Arab Emirates, Dirhams
| |AFA |Afghanistan, Afghanis
| |ALL |Albania, Leke
| |… |
| |ZAR |South Africa, Rand
| |ZMK |Zambia, Kwacha
| |ZWD |Zimbabwe, Zimbabwe Dollars
|Site-specific extension |HL7 |HL7 Events, Drink Ticket
|===

Collectively, this value set must be referred to with a local coding system ID, because “HL7” does not exist in ISO 4217. According to the rules, the site assigns the coding system ID “99CUR” to the value set.

.Based on the code and descriptive text entered by the user on the sending system, the CWE would be populated as follows:
[width="99%",cols="15%,17%,20%,24%,24%",options="header",]
|===
|*Entered by user* | |*Sent in CWE* | |
|*Code* |*Descriptive Text* |*Identifier Code (CWE.1)* |*Descriptive Text (CWE.2)* |*Coding System (CWE.3)*
|GBP |Great Britain, Pound |GBP |Great Britain, Pound |ISO4217
| | |GBP |Great Britain, Pound |99CUR (This option is NOT recommended)
|HL7 |HL7 Drink Ticket |HL7 |HL7 Drink Ticket |99CUR
|XXX |<Bogus entry> |Must not be populated |XXX |Must not be populated.
| | |Must not be populated |Bogus entry |Must not be populated.
| | |Must not be populated |XXX: Bogus entry |Must not be populated.
| | |Must not be populated |anything – or nothing. |Must not be populated.
| |Dollar |Must not be populated |Dollar |Must not be populated.
| | |Valued from HL7 Table 0353 (e.g., “U” for unknown) |Dollar |HL70353
|===

[NOTE]
s:

{empty}1. Where multiple valid options for sending the entered data exist, each alternative is depicted as a separate row.

{empty}2. _CWE.2 - Descriptive Text_ is never required, and there are no hard and fast rules on what text may be sent in this component. Of course, common sense suggests that if valued, the text should complement the identifier code of _CWE.1_.

It follows that where _CWE.1_ cannot be valued because the entered code does not exist in the value set, the entered code _may_ be sent in _CWE.2_; with or without additional descriptive text. However, this is not required by HL7.

{empty}3. The example with GBP shows two options for the code set: ISO4217 or 99CUR. While it is now technically possible to send 99CUR on the basis that this code may exist on its own in the extended local code set, HL7 urges that where a code is a member of the standard code set, that code set should be named in _CWE.3_. HL7 intends to mandate this in a future release.

{empty}4. While there are no formal rules regarding the valuation of _CWE.2 - Descriptive Text_, it is expected that any value contained therein be meaningful to a human reader.

include::CWE-components/CWE-1.adoc[]

include::CWE-components/CWE-2.adoc[]

include::CWE-components/CWE-3.adoc[]

include::CWE-components/CWE-4.adoc[]

include::CWE-components/CWE-5.adoc[]

include::CWE-components/CWE-6.adoc[]

include::CWE-components/CWE-7.adoc[]

include::CWE-components/CWE-8.adoc[]

include::CWE-components/CWE-9.adoc[]

include::CWE-components/CWE-10.adoc[]

include::CWE-components/CWE-11.adoc[]

include::CWE-components/CWE-12.adoc[]

include::CWE-components/CWE-13.adoc[]

include::CWE-components/CWE-14.adoc[]

include::CWE-components/CWE-15.adoc[]

include::CWE-components/CWE-16.adoc[]

include::CWE-components/CWE-17.adoc[]

include::CWE-components/CWE-18.adoc[]

include::CWE-components/CWE-19.adoc[]

include::CWE-components/CWE-20.adoc[]

include::CWE-components/CWE-21.adoc[]

include::CWE-components/CWE-22.adoc[]

