= (PL) Data Type - person location
:v291_section: 2A.2.54
:v2type: 'Data Type'
:code: PL
:name: person location
:primitive: false
:generated: Thu, 19 Sep 2024 15:32:58 -0600

[datatype-definition]
This data type is used to specify a patient location within a healthcare institution. Which components are valued depends on the needs of the site. For example for a patient treated at home, only the person location type is valued. It is most commonly used for specifying patient locations, but may refer to other types of locations within a healthcare setting.

[NOTE]
This data type contains several location identifiers that should be thought of in the following order from the most general to the most specific: facility, building, floor, point of care, room, bed. +
Additional data about any location defined by these components can be added in the following components: person location type, location description and location status.

[example]
Nursing Unit

A nursing unit at Community Hospital: 4 East, room 136, bed B

4E^136^B^CommunityHospital^^N^^^

[example]
Clinic

A clinic at University Hospitals: Internal Medicine Clinic located in the Briones building, 3^rd^ floor.

InternalMedicine^^^UniversityHospitals^^C^Briones^3^

[example]
Home

The patient was treated at his home.

[er7]
^^^^^H^^^

include::PL-components/PL-1.adoc[]

include::PL-components/PL-2.adoc[]

include::PL-components/PL-3.adoc[]

include::PL-components/PL-4.adoc[]

include::PL-components/PL-5.adoc[]

include::PL-components/PL-6.adoc[]

include::PL-components/PL-7.adoc[]

include::PL-components/PL-8.adoc[]

include::PL-components/PL-9.adoc[]

include::PL-components/PL-10.adoc[]

include::PL-components/PL-11.adoc[]

