= (PRL) Data Type - parent result link
:v291_section: 2A.2.57
:v2type: 'Data Type'
:code: PRL
:name: parent result link
:primitive: false
:generated: Thu, 19 Sep 2024 15:32:58 -0600

[datatype-definition]
Uniquely identifies the parent result’s OBX segment related to the current order, together with the information in _OBR-29 - Parent_.

*Usage Note:* This data type is applied only to _OBR-26 - Parent Result_ where it serves to make information available for other types of linkages (e.g., toxicology). This important information, together with the information in _OBR-29 - Parent_, uniquely identifies the parent result’s OBX segment related to this order. The value of this OBX segment in the parent result is the organism or chemical species about which this battery reports. For example, if the current battery is an antimicrobial susceptibility, the parent results identified OBX contains a result that identifies the organism on which the susceptibility was run. This indirect linkage is preferred because the name of the organism in the parent result may undergo several preliminary values prior to finalization.

We emphasize that this field does not take the entire result field from the parent. It is meant only for the text name of the organism or chemical subspecies identified. This field is included only to provide a method for linking back to the parent result for those systems that could not generate unambiguous Observation IDs and sub-IDs.

This field is present only when the parent result is identified by _OBR-29 - Parent_ and the parent spawns child orders for each of many results. See Chapter 7, "Observations", for more details about this linkage.

[NOTE]
Replaces the CM data type used in sections 4.5.3.26 - OBR-26 and 7.4.1.26 - OBR-26 as of v 2.5.

include::PRL-components/PRL-1.adoc[]

include::PRL-components/PRL-2.adoc[]

include::PRL-components/PRL-3.adoc[]

