= Message - M05 Patient Location Master File
:v291_section: "8.9.1"
:v2_section_name: "MFN/MFK - Patient Location Master File Message (event M05)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

This section is specifically concerned with describing a master file message that should be used to transmit information which identifies the inventory of healthcare patient locations, such as nursing units, rooms, beds, clinics, exam rooms, etc. In a network environment, this segment can be used to define patient locations to other applications. The segment also includes the readiness states and support locations for the patient locations.

The LOC, LCH, LRL, LDP, and LCC segments must be preceded by the MFI and MFE segments, as described in Section 8.5, "GENERAL MASTER FILE SEGMENTS." In the following message, the _MFI-1 - Master File Identifier_ field should equal "LOC"

[tabset]

When the LCH segment appears immediately following the LOC segment, it communicates characteristics which are the same across multiple departments that may use the same room. When the LCH segment appears immediately following the LDP segment, it communicates characteristics which differ for different departments that may use the same room.

[tabset]



