= Message - M06 Clinical Trials Master File
:v291_section: "8.11.1"
:v2_section_name: "MFN/MFK - Clinical Trials Master File Message (Event M06-M07)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

The CM0 (Clinical Study Master), CM1 (Clinical Study Phase), and CM2 (Clinical Study Schedule) segments can be used to transmit master files information between systems. The CM0 segment contains the information about the study itself; the CM1 contains the information about one phase of the study identified in the preceding CM0; and the CM2 contains the information about the scheduled time points for the preceding study or phase-related treatment or evaluation events. When these segments are used in an MFN message, the abstract definition is described below.

*Case 1: MFN message for Clinical Study with phases and schedules*

_MFI-1 - Master File Identifier Code_ = CMA

[message_structure-table]

[ack_chor-table]

[message_structure-table]

[ack_chor-table]

*Case 2: MFN message for Clinical Study without phases but with schedules*

_MFI-1 - Master File Identifier Code_ = CMB

[message_structure-table]

[ack_chor-table]

[message_structure-table]

[ack_chor-table]

