= Message - M14 Master File Notification - Site Defined
:v291_section: "8.4.3"
:v2_section_name: "MFN/MFK - Master File Notification - Site Defined (Event M14) "
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

[v291_section="8.4"]
The MFN Site defined master file notification transaction is used where the master file is not a simple one (as defined for MFN^M13) and is not a transaction type currently defined by HL7, but rather requires one or more HL7 and/or 'Z' segments to carry the master file information.

[tabset]
M14

=== MFN Use Note ===

The master file record identified by the MFE segment is contained in Z-segments immediately following the MFE segment, and is denoted by "..." in the MFN abstract message definition given above. This record may be either a flat record contained in a single segment, or a complex record needing more than a single segment to carry its data and (usually hierarchical) structure.

The definition of this transaction and the associated abstract message structure code (as defined in MSH-9 - Message Type, denoted by MFN_Znn above) are subject to site negotiation. Refer to Chapter 2, section 2.17, "Local Extension" for additional information on 'Z' abstract message structure code definition.

=== MFK Use Note ===

The MFA segment carries acknowledgment information for the corresponding MFE segment (identified by MFA-5 - Primary Key Value - MFA). Fields MFE-4 - Primary Key Value - MFE and MFA-5 - Primary Key Value - MFA provide the link between the corresponding segments.
