= Pharmacy/Treatment Dispense Request
:v291_section: "4A.3.24"
:v2_section_name: "RDE - Pharmacy/Treatment Dispense Request Message (Event O49)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

This message communicates the request to dispense items. It may be sent as a consequence of an existing order. It may not follow the order immediately: The pharmacist receives clinical orders continuously, but may decide that the orders for dispense are sent periodically. This illustrates that there is a new event.

This message is also not required to contain the order in its entirety: for example if one RDE^O11 contains 3 medications order there are 3 dispensing locations, the pharmacist issues one RDE^O49 for each medication. Any supply aspects are handled through these new types of message, while the clinical order can be segregated from such supply constraints.

The order to dispense refers to the “clinical” order, the original RDE^O25 (or OMP^O09) by means of a parent-child hierarchy, where ORC-8 of the OXX message refers to the ORC-2 of the RDE^025 order.

[message_structure-table]

[NOTE]


The RXCs which follow the RXO may not be fully encoded, but those that follow the RXE must be fully encoded.

The NTE segment(s) following the PD1 segment are intended to communicate notes and comments relative to the patient.

The NTE segment(s) following the RXO segment are intended to communicate notes and comments relative to the pharmacy/treatment order.

The NTE segment(s) following the RXE segment are intended to communicate notes and comments relative to the encoded order.

The NTE segment(s) following the RXC segment are intended to communicate notes and comments relative to the component(s).

[ack_chor-table]

