= Materials Management

== Introduction
[v291_section="17.3"]

This Materials Management topic defines abstract messages for the purpose of communicating various events related to the transactions derived from supply chain management within a healthcare facility.

The sterilization (GLOSSARY) and decontamination (GLOSSARY) messages are based on a request, response, or unsolicited update. These transactions occur between an instrument-tracking system and a sterilizer (GLOSSARY) or washer (GLOSSARY).

This topic describes various roles under which applications might operate. The roles discussed here illustrate the underlying model used to develop this specification. They do not imply the need for a particular application model or method of implementation.

== General Use Cases / Background

=== Sterilization and Decontamination
[v291_section="17.3.2"]

The main focus of the sterilization and decontamination process is a load or grouping of _supply items_. These messages communicate sterilizer configuration, sterilizer lot, and device and cycle data messages related to instances of sterilizing and decontaminating supply items.

_Sterilization_ is a process used to render a product free from viable microorganisms in order to meet infection prevention standards. Sterilizers are defined as apparatus used to sterilize medical devices, equipment and supplies by direct exposure to the sterilizing agent. The typical sterilizing agent for high temperature sterilization is saturated steam under pressure; low temperature sterilizing agents are peracetic acid or ethylene oxide (EO) gas (GLOSSARY).

_Decontamination_ is defined by the Occupational Safety and Health Administration (OSHA) as the use of physical or chemical means to remove, inactivate or destroy blood-borne pathogens on a surface or item to the point where they are no longer capable of transmitting infectious particles and the surface or item is rendered safe for handling, use or disposal. {29 CFR 1910.1030} Washers provide decontamination services in order to render items safe for handling.

Steam sterilizers have defined cycles (GLOSSARY) that achieve sterilization by attaining certain temperatures for specific lengths of time (GLOSSARY - point to Cycle Time). These cycles are validated using Association for Advancement of Medical Instrumentation (AAMI) standards.

Ethylene oxide gas and peracetic acid sterilizers have defined cycles that are validated by the manufacturer's research to achieve sterilization at specific temperatures and exposure times to the sterilant.

Sterilization and decontamination cycles (GLOSSARY) are defined as a sequence of steps or phases that are designed to achieve sterilization or decontamination.

Typical phases for steam sterilization include Condition, Sterilize and Exhaust. Phases for ethylene oxide sterilization include Condition, Sterilize, Exhaust and Aerate. Peracetic acid sterilizers also have similar phases.

The following tables contain examples of typical cycles for sterilizers and washers.

.Representative Steam Sterilization Cycles
[width="100%",cols="16%,18%,13%,15%,38%",options="header",]
|===
|Cycles |Sterilize Temperature |Sterilize Time |Dry Time |Recommended Load
|Express |270°F (132°C) |4.0 min |3.0 min |Single wrapped instrument tray with a single instrument. Non-porous good, only.
|Flash |270°F (132°C) |3.0 min |1.0 min |Unwrapped instrument tray with a single instrument
|===

.Prevacuum Testing Cycles for Steam Sterilizers
[width="100%",cols="22%,20%,17%,17%,24%",options="header",]
|===
|Prevacuum Testing Cycles |Sterilizer Temperature |Sterilize Time |Dry Time |Recommended Load
|Leak Test |270°F (132°C) |N/A |N/A |N/A
|Dart Test |270°F (132°C) |3.5 min |1.0 min |Bowie-Dick Test (GLOSSARY) or DART
|Dart Warmup |270°F (132°C) |3.0 min |1.0 min |N/A
|===

=== Application roles
[v291_section="17.3.3"]

In the sterilization and decontamination specification, there are two roles that an application can assume: a filler application role, and a placer application role. These application roles define the interaction that an application will have with other applications in the messaging environment. In many environments, any one application may take on more than one application role.

In this specification, the definition of application roles is not intended to define or limit the functionality of specific products developed by vendors of such applications. Instead, this information is provided to help define the model used to develop this specification, and to provide an unambiguous way for applications to communicate with each other.

== Implementation Considerations

=== Trigger Events
[v291_section="17.4"]

This topic defines trigger events used to communicate supply item information between applications. The sterilization and decontamination related trigger events are defined in section _17.5_, "_Inventory Item Master Messages Segments_," and _17.6_, "_Placer Application Requests and Trigger Events_."

=== Statuses
[v291_section="17.4.1"]

The status of a load describes the state of a load during a sterilization cycle. Typical statuses of a load may include the following: Pending, Active, Complete, and Canceled.

=== Trigger Events and Message Definitions
[v291_section="17.4.3"]

This specification contains functional groupings of trigger events and message definitions. The trigger events within each functional grouping share the same or similar message definitions.

The first functional grouping of trigger events and message definitions describes _placer request transactions_. This grouping defines the trigger events and message definitions for transactions from applications acting in a placer application role, and also defines the related filler application response messages sent back by applications fulfilling the auxiliary role. These messages are described in section _17.6_, "_Placer Application Requests and Trigger Events_."

The second functional grouping describes trigger events and message definitions for _unsolicited transactions_ from applications acting in the filler application role. This grouping describes the unsolicited messages originating from an application fulfilling the filler role, and the response messages sent back by applications fulfilling the auxiliary role. These messages are described in section _17.7_, "_Filler Application Messages and Trigger Events Unsolicited_."

==== Update mode
[v291_section="17.4.3.0"]

This topic uses the "Action code/unique identifier" mode for updating via repeating segments. For more information on updating via repeating segments, please see section 2.15.4, "Modes for updating via repeating segments," in Chapter 2. The definition of the "Action code/unique identifier" update mode can be found in Chapter 2, section 2.15.4.2, "Action code/unique identifier mode update definition."

== Technical Specs

=== Placer Application Requests and Trigger Events
[v291_section="17.6"]

Placer request and filler response transactions are the messages and trigger events used between placer applications and filler applications. The placer application initiates transactions using the *SLR*, *STI*, *SDR,* or *SMD* message types, requesting information with the given trigger event message detail. The filler application responds to these requests, using the *SLS*, *STS*, *SDS,* or *SMS* message types, to either grant or deny the requests from the placer application.

When initiating a request, the placer application will generate and send a message type containing all of the information necessary to communicate the desired action to the filler application. All required segments and fields (both explicitly required and conditionally required) should be provided to the filler application, as defined here. When the filler application receives the transaction, it acknowledges it with the appropriate accept acknowledgment using an *ACK* message (assuming that the enhanced acknowledgment mode is in use).

After processing the request at the application level, the filler acknowledges the transaction with the appropriate application acknowledgment in a response message type (again assuming that an application acknowledgment was requested under the enhanced acknowledgment mode or that the original acknowledgment mode is in use). Applying the explanations of the various application acknowledgment codes in the context of this topic, an application accept from the filler means that the request was processed and accepted by the filler.

An application error from the filler means that the request was processed and denied. An application reject from the filler means that the request was not, and could not be, processed due to one or more reasons unrelated to its content (for example, it fails the basic application protocol validation, the filler system is down, or there was an internal error).

There are no unsolicited messages initiated from a filler application defined in this set of trigger events. Those messages and trigger events are defined below, in section _17.7_, "_Filler Application Messages and Trigger Events Unsolicited_."

All of the trigger events associated with placer request and filler response transactions use the message definitions that follow:

xref:technical_specs/S28.adoc[Message - S28 Request New Sterilization Lot]

xref:technical_specs/S29.adoc[Message - S29 Request Sterilization Lot Deletion]

xref:technical_specs/S30.adoc[Message - S30 Request Item]

xref:technical_specs/S31.adoc[Message - S31 Request Anti-Microbial Device Data]

xref:technical_specs/S32.adoc[Message - S32 Request Anti-Microbial Device Cycle Data]

=== Filler Application Messages and Trigger Events Unsolicited
[v291_section="17.7"]

Unsolicited transactions from filler applications are the messages and trigger events used between filler applications and auxiliary applications. Transactions are initiated by the filler application, using the *STC* message to notify auxiliary applications of a sterilization configuration set. The auxiliary application responds to these notifications, using the *ACK* message, either to acknowledge receipt of the transaction, or to signal that an interfacing error of some kind has occurred.

As the discussion of application roles has indicated above, any one application can have more than one application role. If it is important that the application acting in the placer application role in your messaging environment be notified of unsolicited sterilization configurations, then it must also support the role of an auxiliary application.

When initiating a notification transaction, the filler application will generate and send an *STC*, *SLN*, *SDN,* or *SCN* message containing all of the information necessary to communicate the desired information to the auxiliary application. All required segments and fields (both explicitly required and conditionally required) should be provided by the filler application. When the auxiliary application receives the transaction, it acknowledges with the appropriate accept acknowledgment using an *ACK* message (assuming that the enhanced acknowledgment mode is in use). After processing the notification at the application level, the auxiliary application acknowledges the transaction with the appropriate application acknowledgment in an *ACK* message (assuming that an application acknowledgment was requested under the enhanced acknowledgment mode or that the original acknowledgment mode is in use). Applying the explanations of the various application acknowledgment codes (detailed in Chapter 2) in this context, an application accept from the auxiliary application means that the notification was processed and accepted. An application error from the auxiliary application means that the auxiliary application was unable to process the notification at the application level. An application reject from the auxiliary application means that the request was not, and could not be, processed due to one or more reasons unrelated to its content (for example, it fails the basic application protocol validation, the system is down, or there was an internal error).

xref:technical_specs/S33.adoc[Message - S33 Notification of Sterilization Configuration]

xref:technical_specs/S34.adoc[Message - S34 Notification of New Sterilization Lot]

xref:technical_specs/S35.adoc[Message - S35 Notification of Sterilization Lot Deletion]

xref:technical_specs/S36.adoc[Message - S36 Notification of Anti-Microbial Device Data]

xref:technical_specs/S37.adoc[Message - S37 Notification of Anti-Microbial Device Cycle Data]

== Examples

=== Request New Sterilization Lot - Event S28
[v291_section="17.10.2"]

The sterilizer operator is preparing to run a flash sterilizer load. The sterilizer requests a lot number from the instrument-tracking system to assign to the load.

[er7]
MSH|^~\&|Sterila|FacilB|Instrutrak|FacilA|202510010800||SLR^S28^SLR_S28|021244STER|P|2.9|||AL|AL
SFT|Hospital A|9.0|Sterila|10101010|9.0 999|New Load|202502140900
UAC|KERB|MATSYS|AP|Octet-stream|A|Clerk
SLT|87995|DEVICE NAME|A46|LF4|1435567677

MSH|^~\&|Sterila|FacilB|Instrutrak|FacilA|202510010800||ACK^S28^ACK|021244STER|P|2.9|||NE|NE
MSA|CA|021244STER

MSH|^~\&|Instrutrak|FacilB|Sterila|FacilA|2025010010801||SLS^S28^SLR_S28|021244STER|P|2.9|||AL|NE
SFT|Hospital A|9.0|Sterila|10101010|9.0 999|New Load|202502140900
UAC|KERB|MATSYS|AP|Octet-stream|A|Admin
SLT|01

MSH|^~\&|Instrutrak|FacilB|Sterila|FacilA|2025010010801||SLS^S28^SLR_S28|021244STER|P|2.9|||NE|NE
MSA|CA|021244STER
