= Message - Query by parameter/display response
:v291_section: "5.4.3"
:v2_section_name: "QBP/RDY – query by parameter/display response (events vary)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

[query_message_structure-table]



The QBP_Q15 structure supports a Display Response and contains the MSH, QPD, RCP, and DSC segments. Its default trigger event is Q15. A standard or site-defined query may use this trigger event or may specify a unique trigger event value in its Query Profile. If a unique trigger event value is chosen for a site-defined query, that value SHALL begin with *Z*.

[response_message_structure-table]



The RDY_K15 supports a Display Response to the QBP and contains the MSH, MSA, ERR, QAK, DSP, and the DSC. Its default trigger event is K15. A standard or site-defined response may use this trigger event or may specify a unique trigger event value in its Query Profile. If a unique trigger event value is chosen for a site-defined response, that value SHALL begin with *Z*.

[NOTE]
The indicated trigger events are the default values for MSH-9-2-Trigger event. Standard and site-defined queries may use these trigger events or may specify unique trigger event values in their Query Profiles. Unique trigger event values for site-defined queries SHALL begin with *Z*.

[NOTE]
on QBP*: Query By Example variant: The query by example is an extension of Query by Parameter (QBP) in which search parameters are passed by sending them in the segment which naturally carries them. A Query Profile which uses this variant SHALL replace the ellipses in the input QBP_Q11 grammar above, with the specific segments that it accepts.

