= Message - Query by parameter/segment pattern response
:v291_section: "5.4.1"
:v2_section_name: "QBP/RSP – query by parameter/segment pattern response (events vary)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

[query_message_structure-table]

[ack_chor-table]

The QBP_Q11 structure supports a Segment Pattern Response and contains the MSH, QPD, RCP, and DSC segments. Its default trigger event is Q11. A standard or site-defined query may use this trigger event or may specify a unique trigger event value in its Query Profile. If a unique trigger event value is chosen for a site-defined query, that value SHALL begin with *Z*.

[response_message_structure-table]

[ack_chor-table]

The RSP_K11 supports a Segment Pattern Response to the QBP and contains the MSH, MSA, ERR, QAK, QPD, variable content segments, and the DSC. Its default trigger event is K11. A standard or site-defined response may use this trigger event or may specify a unique trigger event value in its Query Profile. If a unique trigger event value is chosen for a site-defined response, that value SHALL begin with *Z*.

[NOTE]
on QBP*: Query By Example variant: The query by example is an extension of Query by Parameter (QBP) in which search parameters are passed by sending them in the segment which naturally carries them. A Query Profile which uses this variant SHALL replace the ellipses in the input QBP_Q11 grammar above, with the specific segments that it accepts.

[NOTE]
The indicated trigger events are the default values for MSH-9-2-Trigger event. Standard and site-defined queries may use these trigger events or may specify unique trigger event values in their Query Profiles. Unique trigger event values for site-defined queries SHALL begin with *Z*.

[NOTE]
on RSP:* The Query Profile for each QBP/RSP pair shall specify an explicit segment pattern grammar in place of the ellipses shown above in the RSP_K11 grammar.

