= Message - E03 Query HealthCare Services Invoice Status
:v291_section: "16.3.4"
:v2_section_name: "QBP^E03 – Query HealthCare Services Invoice Status (Event E03)"
// and RSP^E03 – HealthCare Services Invoice Status Query Response (Event E03)
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

This message is used to respond to a QPB^E03 – Query HealthCare Services Invoice. It provides Invoice and invoice processing information to a Provider.

A QBP^E03 – Query HealthCare Services Invoice can be used to query against an Invoice or a specific Product/Service Line Item in an Invoice. The same response message, RSP^E03 – HealthCare Services Invoice Query Response, is used for both types of query.

Processing Rules:

{empty}1) Provider Invoice Number + Payer Invoice Number + Product/Service Line Item Number on input message must exist on Payer Application's database and must point to the same Product/Service Line Item, otherwise an error must be generated (mismatched Invoice and/or Product/Service Line Item).

{empty}2) Sending Organization and Sending Application on input message must be the same as the Sending Organization and Sending Application from the original Invoice (submitted via the EHC^E01 – Submit HealthCare Services Invoice message) for the specified Invoice being queried.

{empty}3) A unique query identifier (Query Tag on QPD) must be generated for each query.

[tabset]
E03
