= Message - E22 Query Authorization Request Statu
:v291_section: "16.3.13"
:v2_section_name: "QBP^E22 – Query Authorization Request Status (event E22); RSP^E22 – Authorization Request Status Query Response (event E22) "
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

This message is used to respond to a QPB^E22 – Query Authorization Request Status. It provides Authorization status information to a Provider.

A QBP^E22 – Query Authorization Request Status can be used to query against a Authorization Request or a specific Product/Service Line Item in a Authorization Request. The same response message, RSP^E22 – Authorization Request Query Response, is used for both types of query.

Processing Rules:

{empty}1) Provider Invoice Number + Payer Invoice Number + Product/Service Line Item Number on input message must exist on Payer Application's database and must point to the same Product/Service Line Item; otherwise, an error must be generated (mismatched Authorization Request and/or Product/Service Line Item).

{empty}2) Sending Organization and Sending Application on input message must be the same as the Sending Organization and Sending Application from the original Authorization Request (submitted via the EHC^E20 – Submit Authorization Request message) for the specified Authorization Request being queried.

{empty}3) A unique query identifier (Query Tag on QPD) must be generated for each query.

[response_message_structure-table]

[ack_chor-table]

