= Message - Unsolicited update individual product experience report
:v291_section: "7.11.1"
:v2_section_name: "PEX - Product Experience Message (Event P08)"
:generated: "Thu, 01 Aug 2024 15:25:17 -0600"

The primary application of this message is to transfer information related to an adverse event occurring while a patient was exposed to a product.

[tabset]
P08

The PID segment provides the patient identification information including institutional identification numbers, date of birth and in the case of patients who die, information about their death. Patients are frequently identified only by their initials which can be represented in the PID segment, e.g., the initials JMO would appear as J^M^O in the name field of the PID segment. The EVN segment identifies the type of transaction that is being sent -- primarily it specifies who the sender is and implies which information is expected to be included in the message. A message sent from a healthcare provider, for example, might contain minimal information, while a message from a pharmaceutical manufacturer might contain nearly complete information.

The PES or Product Experience Sender segment provides information about the message sender and its knowledge of the event. The heart of the product experience message is the product experience observation (PEO) segment and the PCR segments clustered under it. The PEO segment identifies a clinical event and the PCR segments identify products which are potentially causally related to the event. There may be more than one product which is potentially related to the event so multiple PCR segments can be included. RXE and RXR segments can be repeated and provide information about the products the patient was exposed to at the time of the event (typically excluding those used to treat the event). Details about the administration of the products identified in the PCR segments should be described with RXE and RXR segments. Repeated PRB segments provide information about diagnoses which represent comorbid conditions. The repeated OBX segments are used to send patient observations such as height, weight, last menstrual period, and laboratory results. Analytical commentary can be included in the NTE segment. This commentary will typically be the sender's analysis of the event and the potentially causally related products. Finally, the CSR and CSP segments can optionally be included if the event occurred during a formal clinical trial in order to describe the trial.

When a product experience relates to an exposure which occurred indirectly (transmammary or transplacentally for example), the individual experiencing the adverse effect — the fetus or child — would be described in the PID segment and the individual via which they are exposed in the NK1 segment. The first set of RXE segments would typically indicate the drugs which to which the fetus or child was exposed. Additional codes for the route are defined in this Appendix to allow the suspected routes of exposure to be represented. The second set of RXE/RXR segment - those clustered under the NK1 segment - would represent the route by which the mother or father was exposed to the drug. Early spontaneous abortion would normally be treated as an adverse effect on the mother rather than on the fetus, and the PID would refer to the mother. The second set of PRB/OBX segments reflects the problems/observations associated with the individual via which they were exposed.

Each message contains information about a single case including one patient (PID), at least one sender (PES), one or more events (PEO) and one or more suspected products (PCR and RXE/RXA) for a minimal message. The structure of the message allows actual administration information to be sent in the RXA if known; if administration information is unavailable, or the adverse reaction cannot be related to a single administration event, the RXE segment can be used to send prescription level information. Additional information may be included based on availability and regulatory requirements.

The MSH segment specifies the character set (_MSH-18_) and the language (_MSH-19_) used in the PEX message.





