= Clinical Trials

== Introduction
[v291_section="7.6"]

Academic medical institutions, academic research coordinating centers, and industry-based research organizations often have computer systems that support registration, compliance and safety monitoring, and outcomes analysis for clinical trials. Patients on these trials may receive their treatment and evaluation at one research facility or at many different medical facilities. Clinical trials systems could message other applications that a patient is registered on a clinical trial. Several functional examples follow:

{empty}(1) Some of the data required to monitor or analyze outcomes on the trial are generated in other medical computer systems, such as pharmacy, laboratory, or clinical applications. These applications may tag patients on clinical trials so that data may be sent back to the clinical trials system.

{empty}(2) Order entry systems could also use patient registration information: they could display standard order sets for the protocol or particular treatment/evaluation phases of a complex protocol. They could pass the clinical trials status on to service provider applications to initiate a results report to the clinical trials system. It could also be passed to billing applications that may use specialized procedures for research‑related costs.

{empty}(3) Nursing and pharmacy systems can use information on patients' clinical trials status for care plans or dispensing authorization (auxiliary to the physician's prescription), respectively. There could be many other uses of this message since a patient's involvement on a clinical trial affects all concurrent medical care.

To meet monitoring and analysis requirements, patient registration, treatment, diagnostic, and study summary data are reported to study sponsors like pharmaceutical or medical device companies, regulatory agencies, and data management centers for collaborative studies. Automated procedures must be used to transfer these voluminous data among the participant computer systems in a cost-efficient and timely manner. The following additions to HL7 aim to specify standard messaging transactions to automate such reporting as well as to enable communication of clinical trials registration data to relevant medical applications as described above.

The objectives of the clinical trials messages and segments are to identify that patients are registered on clinical trials, have entered a study‑specific phase of treatment or evaluation, or to indicate the study protocol's data schedule. Messages include OBR (section 4.5.3, "OBR - Observation Request Segment"), OBX (section 7.4.2, "OBX ‑ Observation/Result Segment"), RXA (section 4.14.7, "RXA - Pharmacy /Treatment Administration Segment"), and RXR (section 4.14.2, "RXR - pharmacy/Treatment Route Segment") segments to report observations or drug administration that are relevant to the study. In addition to study‑related clinical data, OBX segments may contain the results of study variables according to master code tables such as the Health Outcomes Variables (HL7 Implementation Guide). There are also master segments to describe the clinical trial, its treatment phases, and its scheduled date-time points for message recipients. These are analogous to the Test/Observation Master Segments (Chapter 8), with the trials, phases, or scheduled time points treated as the OMX treats observation identifiers.

== Technical Specs

xref:technical_specs/C01.adoc[Message - C01 Register a patient on a clinical trial]

xref:technical_specs/C02.adoc[Message - C02 Cancel a patient registration on clinical trial (for clerical mistakes since an intended registration should not be canceled)]

xref:technical_specs/C03.adoc[Message - C03 Correct/update registration information]

xref:technical_specs/C04.adoc[Message - C04 Patient has gone off a clinical trial]

xref:technical_specs/C05.adoc[Message - C05 Patient enters phase of clinical trial]

xref:technical_specs/C06.adoc[Message - C06 Cancel patient entering a phase (clerical mistake)]

xref:technical_specs/C07.adoc[Message - C07 Correct/update phase information]

xref:technical_specs/C08.adoc[Message - C08 Patient has gone off phase of clinical trial]

xref:technical_specs/C09.adoc[Message - C09 Automated time intervals for reporting, like monthly]

xref:technical_specs/C10.adoc[Message - C10 Patient completes the clinical trial]

xref:technical_specs/C11.adoc[Message - C11 Patient completes a phase of the clinical trial]

xref:technical_specs/C12.adoc[Message - C12 Update/correction of patient order/result information]

== Examples

=== CRM - Message When Patient Registered on a Clinical Trial
[v291_section="7.9.1"]

[er7]
MSH|^~\&|PDMS|MDACC|ORDER ENTRY|MDACC|200006021649||CRM^C01^CRM_C01|...<cr>
PID|1||2222||Everywoman^Eve^E||19530117|...<cr>
CSR|DM94-004^MDACC||MDACC|3||19941013||342^^^^^^^PDMS| |||||1005^^^^^^^MDACC|19941013|Y^Meets All Requirements^PDMS|...<cr>

=== CRM - Message When Patient Begins a Phase of a Clinical Trial
[v291_section="7.9.2"]

[er7]
MSH|^~\&|PDMS|MDACC|PHARM|MDACC|200006050925||CRM^C05^CRM_C05|...<cr>
PID|1||2222||Everywoman^Eve^E||19230213|...<cr>
CSR|ID91-025^MDACC||MDACC|301||19941005||342^^^^^^^PDMS |||19941201|2^blind^PDMS| 12^Smoker,Stage II,<60^PDMS|...<cr>
CSP|2^Treatment^PDMS|19941201|...<cr>

=== CSU - Message Reporting Monthly Patient Data Updates to the Sponsor
[v291_section="7.9.3"]

[er7]
XYZ...<cr>
*hello*
XYZ...<cr>
&nbsp;&nbsp;&nbsp;&nbsp;hello *[world]*
{empty}hello *[world]*
*[cbc values]*
XYZ...<cr>
OBX|1|NM|718-7^HEMOGLOBIN:^LN||13.4|GM/DL|14-18|N||S|F|19860522|...<cr>
{empty}*[cbc values]*
OBX|2|NM|4544-3^HEMATOCRIT:^LN||40.3|%|42-52|L||S|F|19860522|...<cr>


[er7]
MSH|^~\&|PDMS|MDACC|CTMS|NCI|200006050927||CSU^C09^CRM_C09|...<cr>
OBX|1|CWE|ELIG1^Elig Crit 1^NCI|Text Elig Crit 1|Y|...<cr>
OBX|2|CWE|ELIG2^Elig Crit 2^NCI||Y|...<cr>
OBR|2|1235|1235|4^Prestudy Form^StudyFormsList|||19941205|...<cr>
OBX|1|CWE|QOL^Quality of Life^NCI||2\T\3\T\2\T\4\T\2^SPITZER|...<cr>
OBX|2|CWE|PRICHEM^Prior Chemo^NCI||Yes|...<cr>
OBX|3|CWE|PRIBIOL^Prior Biologics^NCI||No|...<cr>
OBX|4|NM|NUMREM^Number Prior Remissions^NCI||2|...<cr>
OBR|3|932^OE|243789^LAB|88304^SURG PATH REPORT|||19940101|...<cr>
OBX|1|CWE|88304&ANT|1|9999^PANCREAS^SNM|...<cr>
OBX|2|CWE|88304&IMP|2|9999^ADENOCARCINOMA^SNM|...<cr>
OBR|4|933^OE|243790^LAB|85022^CBC|||199412050800|...<cr>
OBX|1|NM|718-7^HEMOGLOBIN:^LN||13.4|GM/DL|14-18|N||S|F|19860522|...<cr>
{empty}*[cbc values]*
OBX|2|NM|4544-3^HEMATOCRIT:^LN||40.3|%|42-52|L||S|F|19860522|...<cr>

[er7]
OBX|3|NM|789-8^ERYTHROCYTES:^LN||4.56|10\*6/ml|4.7-6.1|L||S|F|19860522|...<cr>
OBX|4|NM|787-22^ERYTHROCYTE MEAN CORPUSCULAR VOLUME:^LN||88|fl |80-94|N||S|F|19860522|...<cr>
OBX|5|NM|785-6^ERYTHROCYTE MEAN CORPUSCULAR HEMOGLOBIN:^LN||29.5|pg |27-31|N||N|F|19860522|...<cr>
OBX|6|NM|786-4^ERYTHROCYTE MEAN CORPUSCULAR HEMOGLOBIN CONCENTRATION:^LN||33|%|33-37|N||N|F|19860522|...<cr>
OBX|7|NM|6690-2^LEUKOCYTES:^LN||10.7|10\*3/ml|4.8-10.8|N||N|F|19860522|...<cr>
OBX|8|NM|764-1^NEUTROPHILS BAND FORM/100 LEUKOCYTES:^LN||2|%|||||F|...<cr>
OBX|9|NM|769-0^NEUTROPHILS SEGMENTED/100 LEUKOCYTES:^LN||67|%|||||F |...<cr>
OBX|10|NM|736-9^LYMPHOCYTES/100 LEUKOCYTES:^LN||29|%|||||F|...<cr>
OBX|11|NM|5905-5^MONOCYTES/100 LEUKOCYTES:^LN||1|%|||||F|...<cr>
OBX|12|NM|713-8^EOSINOPHILS/100 LEUKOCYTES:^LN||2|%|||||F|...<cr>
OBR|5|934^OE|243791^LAB|80004^ELECTROLYTES|||199412050800|...<cr>
OBX|1|NM|2947-0^SODIUM:^LN||150|mmol/l|136-148|H||A|F|19850301 |...<cr>
OBX|2|NM|2823-3^POTASSIUM:^LN||4.5|mmol/l|3.5-5|N||N|F|19850301|...<cr>
{empty}*[electrolytes values]*
OBX|3|NM|2069-3^CHLORIDE:^LN||102|mmol/l|94-105|N||N|F|19850301|...<cr>
OBX|4|NM|2028-9^CARBON DIOXIDE.TOTAL:^LN||27|mmol/l|24-31|N||N|F |19850301|...<cr>
CSP|^Course 1|19941205|19950120|Y^Toxicity and Response^NCI |...<cr>
CSS|^Course Completion|19950120|...<cr>
OBR|1|935^OE|243791^LAB|2039-6^CARCINOEMBRYONIC AG:^LN|||19941008|...<cr>
OBX|1|NM|2039-6^CARCINOEMBRYONIC AG:^LN||15.2|IU |...<cr>
OBR|2|1236|1236|10^Course Completion Form^StudyPhaseFormsList|||19950120 |...<cr>
OBX|1|CWE|CRSRESP^Course Response^NCI||4^Partial Response|...<cr>
OBX|2|NM|DRUGDISP^Capsules Dispensed^NCI||60|...<cr>
OBX|3|NM|DRUGRETN^Capsules Returned^NCI||5|...<cr>
OBX|4|ID|DXCOMP^Diagnostic Tests Compliance^NCI||Y|...<cr>
OBX|5|CWE|PERSTAT^Performance Status^NCI||3^ZUBRODS|...<cr>
OBR|3|1237|1237|9999^Adverse Events|...<cr>
OBX|1|CWE|9999&EVENT|1|45^Vomiting^NCI|...<cr>
OBX|2|DT|9999&ONSET|1|19941215|...<cr>
OBX|3|DT|9999&RESOLUTION|1|19941217|...<cr>
OBX|4|CWE|9999&GRADE|1|M^MODERATE|...<cr>
OBX|5|CWE|9999&RELATION_TO_RX|1|L^LIKELY|...<cr>
OBX|6|CWE|9999&EVENT|2|303^Dyspnea^NCI|...<cr>
OBX|7|DT|9999&ONSET|2|19941231|...<cr>
OBX|8|DT|9999&RESOLUTION|2|...<cr>
OBX|9|CWE|9999&GRADE|2|MI^MILD|...<cr>
OBX|10|CWE|9999&RELATION_TO_RX|2|U^UNLIKELY|...<cr>

[er7]
MSH|^~\&|PDMS|MDACC|CTMS|NCI|200006050927||CSU^C09^CRM_C09|...<cr>
PID|1||235925||J^F^M||19350616|...<cr> [note:anonymous]
CSR|T93-080^NCI|ID93-030^^MDACC|MDACC|14||19941205|...<cr>
CSS|^Prestudy|19941204|C^compliant^NCI<cr>
OBR|1|1234|1234|3^EligibilChecklist^StudyFormsList|||19941205|...<cr>
{empty}Note: The clinical trials section probably needs its own definition of OBR. OBR-2&3 have condition rules indicating that the placer and filler numbers must be present in either the ORC or the OBR. Since an ORC is not present, then these fields must be populated in the OBR. My guess is that clinical trials aren't interested in the placer and filler number.**
OBX|1|CWE|ELIG1^Elig Crit 1^NCI|Text Elig Crit 1|Y|...<cr>
OBX|2|CWE|ELIG2^Elig Crit 2^NCI||Y|...<cr>
OBR|2|1235|1235|4^Prestudy Form^StudyFormsList|||19941205|...<cr>
OBX|1|CWE|QOL^Quality of Life^NCI||2\T\3\T\2\T\4\T\2^SPITZER|...<cr>
OBX|2|CWE|PRICHEM^Prior Chemo^NCI||Yes|...<cr>
OBX|3|CWE|PRIBIOL^Prior Biologics^NCI||No|...<cr>
OBX|4|NM|NUMREM^Number Prior Remissions^NCI||2|...<cr>
OBR|3|932^OE|243789^LAB|88304^SURG PATH REPORT|||19940101|...<cr>
OBX|1|CWE|88304&ANT|1|9999^PANCREAS^SNM|...<cr>
OBX|2|CWE|88304&IMP|2|9999^ADENOCARCINOMA^SNM|...<cr>
OBR|4|933^OE|243790^LAB|85022^CBC|||199412050800|...<cr>
OBX|1|NM|718-7^HEMOGLOBIN:^LN||13.4|GM/DL|14-18|N||S|F|19860522|...<cr>
{empty}*[cbc values]*
OBX|2|NM|4544-3^HEMATOCRIT:^LN||40.3|%|42-52|L||S|F|19860522|...<cr>
OBX|3|NM|789-8^ERYTHROCYTES:^LN||4.56|10*6/ml|4.7-6.1|L||S|F|19860522|...<cr>
OBX|4|NM|787-22^ERYTHROCYTE MEAN CORPUSCULAR VOLUME:^LN||88|fl |80-94|N||S|F|19860522|...<cr>
OBX|5|NM|785-6^ERYTHROCYTE MEAN CORPUSCULAR HEMOGLOBIN:^LN||29.5|pg |27-31|N||N|F|19860522|...<cr>
OBX|6|NM|786-4^ERYTHROCYTE MEAN CORPUSCULAR HEMOGLOBIN CONCENTRATION:^LN||33|%|33-37|N||N|F|19860522|...<cr>
OBX|7|NM|6690-2^LEUKOCYTES:^LN||10.7|10*3/ml|4.8-10.8|N||N|F|19860522|...<cr>
OBX|8|NM|764-1^NEUTROPHILS BAND FORM/100 LEUKOCYTES:^LN||2|%|||||F|...<cr>
OBX|9|NM|769-0^NEUTROPHILS SEGMENTED/100 LEUKOCYTES:^LN||67|%|||||F |...<cr>
OBX|10|NM|736-9^LYMPHOCYTES/100 LEUKOCYTES:^LN||29|%|||||F|...<cr>
OBX|11|NM|5905-5^MONOCYTES/100 LEUKOCYTES:^LN||1|%|||||F|...<cr>
OBX|12|NM|713-8^EOSINOPHILS/100 LEUKOCYTES:^LN||2|%|||||F|...<cr>
OBR|5|934^OE|243791^LAB|80004^ELECTROLYTES|||199412050800|...<cr>
OBX|1|NM|2947-0^SODIUM:^LN||150|mmol/l|136-148|H||A|F|19850301 |...<cr>
OBX|2|NM|2823-3^POTASSIUM:^LN||4.5|mmol/l|3.5-5|N||N|F|19850301|...<cr>
{empty}*[electrolytes values]*
OBX|3|NM|2069-3^CHLORIDE:^LN||102|mmol/l|94-105|N||N|F|19850301|...<cr>
OBX|4|NM|2028-9^CARBON DIOXIDE.TOTAL:^LN||27|mmol/l|24-31|N||N|F |19850301|...<cr>
CSP|^Course 1|19941205|19950120|Y^Toxicity and Response^NCI |...<cr>
CSS|^Course Completion|19950120|...<cr>
OBR|1|935^OE|243791^LAB|2039-6^CARCINOEMBRYONIC AG:^LN|||19941008|...<cr>
OBX|1|NM|2039-6^CARCINOEMBRYONIC AG:^LN||15.2|IU |...<cr>
OBR|2|1236|1236|10^Course Completion Form^StudyPhaseFormsList|||19950120 |...<cr>
OBX|1|CWE|CRSRESP^Course Response^NCI||4^Partial Response|...<cr>
OBX|2|NM|DRUGDISP^Capsules Dispensed^NCI||60|...<cr>
OBX|3|NM|DRUGRETN^Capsules Returned^NCI||5|...<cr>
OBX|4|ID|DXCOMP^Diagnostic Tests Compliance^NCI||Y|...<cr>
OBX|5|CWE|PERSTAT^Performance Status^NCI||3^ZUBRODS|...<cr>
OBR|3|1237|1237|9999^Adverse Events|...<cr>
OBX|1|CWE|9999&EVENT|1|45^Vomiting^NCI|...<cr>
OBX|2|DT|9999&ONSET|1|19941215|...<cr>
OBX|3|DT|9999&RESOLUTION|1|19941217|...<cr>
OBX|4|CWE|9999&GRADE|1|M^MODERATE|...<cr>
OBX|5|CWE|9999&RELATION_TO_RX|1|L^LIKELY|...<cr>
OBX|6|CWE|9999&EVENT|2|303^Dyspnea^NCI|...<cr>
OBX|7|DT|9999&ONSET|2|19941231|...<cr>
OBX|8|DT|9999&RESOLUTION|2|...<cr>
OBX|9|CWE|9999&GRADE|2|MI^MILD|...<cr>
OBX|10|CWE|9999&RELATION_TO_RX|2|U^UNLIKELY|...<cr>

{empty}[Note: Needs to maintain compatibility with ongoing product experience message efforts.]

{empty}[Note2: There are other possible OBX suffixes defined by FDA: APEX/ NADIR, ACTION, THERAPY, OUTCOME, RECHALLENGE.]
