= Clinical Trials

== Introduction
[v291_section="7.6"]

Academic medical institutions, academic research coordinating centers, and industry-based research organizations often have computer systems that support registration, compliance and safety monitoring, and outcomes analysis for clinical trials (GLOSSARY). Patients on these trials may receive their treatment and evaluation at one research facility or at many different medical facilities. Clinical trials systems could message other applications that a patient is registered on a clinical trial. Several functional examples follow:

* Some of the data required to monitor or analyze outcomes on the trial are generated in other medical computer systems, such as pharmacy, laboratory, or clinical applications. These applications may tag patients on clinical trials so that data may be sent back to the clinical trials system.

* Order entry systems could also use patient registration information: they could display standard order sets for the protocol or particular treatment/evaluation phases (GLOSSARY) of a complex protocol. They could pass the clinical trials status on to service provider applications to initiate a results report to the clinical trials system. It could also be passed to billing applications that may use specialized procedures for research‑related costs.

* Nursing and pharmacy systems can use information on patients' clinical trials status for care plans or dispensing authorization (auxiliary to the physician's prescription), respectively. There could be many other uses of this message since a patient's involvement on a clinical trial affects all concurrent medical care.

To meet monitoring and analysis requirements, patient registration, treatment, diagnostic, and study summary data are reported to study sponsors like pharmaceutical or medical device companies, regulatory agencies, and data management centers for collaborative studies. Automated procedures must be used to transfer these voluminous data among the participant computer systems in a cost-efficient and timely manner. This topic aims to specify standard messaging transactions to automate such reporting as well as to enable communication of clinical trials registration data to relevant medical applications as described above.

The objectives of the clinical trials messages and segments are to identify that patients are registered on clinical trials, have entered a study‑specific phase of treatment or evaluation, or to indicate the study protocol's data schedule (GLOSSARY). Message components include OBR (section 4.5.3, "OBR - Observation Request Segment"), OBX (section 7.4.2, "OBX ‑ Observation/Result Segment"), RXA (section 4.14.7, "RXA - Pharmacy /Treatment Administration Segment"), and RXR (section 4.14.2, "RXR - pharmacy/Treatment Route Segment") segments to report observations or drug administration that are relevant to the study. In addition to study‑related clinical data, OBX segments may contain the results of study variables according to master code tables. There are also master segments to describe the clinical trial, its treatment phases, and its scheduled date-time points for message recipients. These are analogous to the Test/Observation Master Segments (Chapter 8), with the trials, phases, or scheduled time points treated as the OBX treats observation identifiers.

== Technical Specs

xref:technical_specs/C01.adoc[Message - C01 Register a patient on a clinical trial]

xref:technical_specs/C02.adoc[Message - C02 Cancel a patient registration on clinical trial]

xref:technical_specs/C03.adoc[Message - C03 Correct/update registration information]

xref:technical_specs/C04.adoc[Message - C04 Patient has gone off a clinical trial]

xref:technical_specs/C05.adoc[Message - C05 Patient enters phase of clinical trial]

xref:technical_specs/C06.adoc[Message - C06 Cancel patient entering a phase]

xref:technical_specs/C07.adoc[Message - C07 Correct/update phase information]

xref:technical_specs/C08.adoc[Message - C08 Patient has gone off phase of clinical trial]

xref:technical_specs/C09.adoc[Message - C09 Automated time intervals for reporting, like monthly]

xref:technical_specs/C10.adoc[Message - C10 Patient completes the clinical trial]

xref:technical_specs/C11.adoc[Message - C11 Patient completes a phase of the clinical trial]

xref:technical_specs/C12.adoc[Message - C12 Update/correction of patient order/result information]

== Examples

=== CRM - Message When Patient Registered on a Clinical Trial
[v291_section="7.9.1"]

[er7]
MSH|^~\&|PDMS|MDACC|ORDER ENTRY|MDACC|202506021649||CRM^C01^CRM_C01|...
PID|1||2222^^^^^MR||Everywoman^Eve^E||19730117|...
CSR|DM94-004^MDACC||MDACC|3||19941013||342^^^^^^^PDMS| |||||1005^^^^^^^MDACC|19941013|Y^Meets All Requirements^PDMS|...

=== CRM - Message When Patient Begins a Phase of a Clinical Trial
[v291_section="7.9.2"]

[er7]
MSH|^~\&|PDMS|MDACC|PHARM|MDACC|202506050925||CRM^C05^CRM_C05|...
PID|1||2222^^^^^MR||Everywoman^Eve^E||19230213|...
CSR|ID91-025^MDACC||MDACC|301||19941005||342^^^^^^^PDMS |||19941201|2^blind^PDMS| 12^Smoker,Stage II,<60^PDMS|...
CSP|2^Treatment^PDMS|19941201|...
