= Claims And Reimbursements

== Introduction
[v291_section="16.2"]

This document contains the HL7 messaging specifications to support Claims and Reimbursement (CR) for the electronic exchange of health invoice (claim) data. The document is intended for use by benefit group vendors, Third Party Administrators (TPA) and Payers who wish to develop software that is compliant with an international standard for the electronic exchange of claim data.

The content of this document is not intended to be an alternative to or replacement for those ASC X12 standards mandated for use in this domain in the United States

== General Use Cases / Background
[v291_section="16.2.1"]

The scope of the Claims and Reimbursement informative document defines the HL7 messaging and technical standards for:

• Electronic transmission of healthcare invoices, with supporting documents and reports, to authorized individuals and/or organizations;

• Inclusion of diagnostic and preventative intervention codes with each healthcare invoice;

• A query mechanism to allow authorized users to electronically inquire about information they have previously provided to a Payer;

• Minimum data sets;

• Minimum display and print standards; and

• Minimum data storage.

As used in this document the domain of Claims and Reimbursement excludes:

• Payer and benefit group specific processing and implementation rules;

• Jurisdictional specific processing and implementation rules;

• Processes for the submission of supporting documentation by third parties to Payers.

• Processes for the capture and processing of healthcare invoice data by a Provider;

• Processes for the adjudication, payment and reconciliation of healthcare invoices by a Payer;

• Referrals between Providers;

• Electronic funds transfer (EFT) messages; and,

• Implementation of the standard.

== Technical Specs

xref:technical_specs/E01.adoc[Message - E01 Submit HealthCare Services Invoice]

xref:technical_specs/E02.adoc[Message - E02 Cancel HealthCare Services Invoice]

xref:technical_specs/E03.adoc[Message - E03 Query HealthCare Services Invoice Status]

xref:technical_specs/E04.adoc[Message - E04 Re-Assess HealthCare Services Invoice Request]

xref:technical_specs/E10.adoc[Message - E10 Edit/Adjudication Results]

xref:technical_specs/E12.adoc[Message - E12 Request Additional Information]

xref:technical_specs/E13.adoc[Message - E13 Additional Information Response]

xref:technical_specs/E15.adoc[Message - E15 Payment/Remittance Advice]

xref:technical_specs/E20.adoc[Message - E20 Submit Authorization Request]

xref:technical_specs/E21.adoc[Message - E21 Cancel Authorization Request]

xref:technical_specs/E22.adoc[Message - E22 Query Authorization Request Statu]

xref:technical_specs/E24.adoc[Message - E24 Authorization Response]
